### ISSUE TITLE
Assignment Rule Header - how to disable the default rule?

### ISSUE THREAD

**Issue by acccollin** [developerforce/Force.com-Toolkit-for-NET#100]
Hello,

From the sample code below at https://www.salesforce.com/developer/docs/api/index_Left.htm#CSHID=sforce_api_objects_lead.htm|StartTopic=Content%2Fsforce_api_objects_lead.htm|SkinName=webhelp

It is possible to instantiate an AssignmentRuleHeader object and set useDefaultRule to true or false.

Is there any way to accomplish the same using the Toolkit for .NET?

// Create the assignment rule header and add it to the proxy binding
            AssignmentRuleHeader arh = new AssignmentRuleHeader();

            // In this sample we will look for a particular rule and if found
            // use the id for the lead assignment. If it is not found we will
            // instruct the call to use the current default rule. Both these
            // values can't be used together.
            QueryResult qr = binding.query("Select Id from AssignmentRule where Name = " +
                "'Mass Mail Campaign' and SobjectType = 'lead'");
            if (qr.size == 0)
            {
                arh.useDefaultRule = true;
            }
            else
            {
                arh.assignmentRuleId = qr.records[0].Id;
            }
            binding.AssignmentRuleHeaderValue = arh;

Thanks in advance!
Armand Collin

**Comment by acccollin** [comment]
Adding some additional info on the Assignment Rule Header, I would need to set the following:
Sforce-Auto-Assign: FALSE

From:
http://www.salesforce.com/us/developer/docs/api_rest/api_rest.pdf
Page 147

Any way to accomplish that via the Toolkit for .NET?

**Comment by tomajar** [comment]
The salesforce developer docs cannot handle with the direct links to topcis - what a fail :P If you enter first link, use search 'AssignmentRuleHeader' and select first item on the search results - you will find the sample code.

**What framework/library the salesfoce c# example is using?**

```
 public void CreateLead()
        {
            // Create a new Lead and assign various properties
            Lead lead = new Lead();

            lead.FirstName = "John";
            lead.LastName = "Brown";
            lead.Company = "ABC Corporation";
            lead.LeadSource = "Advertisement";
            // Setting the lead source for a pre-existing lead assignment rule. This 
            // rule was created outside of this sample and will assign any new leads
            // that have "Advertisement" as the LeadSource to a particular user

            // Create the assignment rule header and add it to the proxy binding
            AssignmentRuleHeader arh = new AssignmentRuleHeader();

            // In this sample we will look for a particular rule and if found
            // use the id for the lead assignment. If it is not found we will
            // instruct the call to use the current default rule. Both these
            // values can't be used together.
            QueryResult qr = binding.query("Select Id from AssignmentRule where Name = " +
                "'Mass Mail Campaign' and SobjectType = 'lead'");
            if (qr.size == 0)
            {
                arh.useDefaultRule = true;
            }
            else
            {
                arh.assignmentRuleId = qr.records[0].Id;
            }
            binding.AssignmentRuleHeaderValue = arh;

            // Every operation that results in a new or updated lead will use the
            // specified rule until the header is removed from the proxy binding
            SaveResult[] sr = binding.create(new sObject[] { lead });
            foreach (SaveResult s in sr)
            {
                if (s.success)
                {
                    Console.WriteLine("Successfully created Lead with ID: {0}", s.id);
                }
                else
                {
                    Console.WriteLine("Error creating Lead: {0}", s.errors[0].message);
                }
            }

            // This call effectively removes the header. The next lead will be assigned
            // to the default lead owner.
            binding.AssignmentRuleHeaderValue = null;
        }
```

Back to the toolkit - I don't know yet what the 'Assigment Rule Header' is for, but Isn't the problem is, that there is no way to set custom header by the library?

For instance: The service host client

`public class ServiceHttpClient : IServiceHttpClient, IDisposable`

Internally is using 'System.Net.Http.HttpClient'

But this class, or other toolkit classes does not expose any api to set custom headers by the developer?

**Comment by wadewegner** [comment]
That sample is likely working of proxy generated classes from the WSDL and SOAP endpoints.

There's nothing blocking you from doing something yourself. You could even look at the classes generated from the WSDL and use them as the basis for working with the toolkit (which largely uses the REST APIs).
