### ISSUE TITLE
Demo site for WebServerOAuthFlow is offline

### ISSUE THREAD

**Issue by gregbair** [developerforce/Force.com-Toolkit-for-NET#102]
In the README, the URL https://sfdcauth.cloudapp.net/ is given for a demo of this flow.  It does not exist.

**Comment by tomajar** [comment]
I confirm this.

On https://github.com/developerforce/Force.com-Toolkit-for-NET/blob/master/README.md

There is a sentence:

> You can see this demo live here: https://sfdcauth.cloudapp.net/

If you will fix the sample sites builds - you can change the setence ;)

If you will fix the demo on cloud app - maybe add there some kind of version number or synchronize the depoly there with TeamCity build, so it will be always up-to-date.

**Comment by wadewegner** [comment]
Fixed. https://github.com/developerforce/Force.com-Toolkit-for-NET/commit/f22db31e3d4ce9626fc3cdb9ba9435ac4225afaf
