### ISSUE TITLE
How can I actually view documentation for this project?

### ISSUE THREAD

**Issue by v50minasyan** [developerforce/Force.com-Toolkit-for-NET#103]
After spending several hours trying to understand where formal documentation for this project is, I can't find it. It's not in the wiki, it's not in the issues. Does it even exist? If it does, how do I get to it?
Or do I simply read the source code, and that's the only docs available?

This post asks the same questions:
https://developer.salesforce.com/forums/ForumsMain?id=906F0000000B0BeIAK

Are there no plans to get such documentation out? Or is there a way to auto-generate it that I am missing? Thank you!

**Comment by wadewegner** [comment]
Right now there really isn't any documentation. The samples and the unit tests help quite a bit.

**Comment by v50minasyan** [comment]
After reading through the source code, we got up and running pretty well. Thanks for the project - it's been a real big help!

**Comment by wadewegner** [comment]
Glad to hear it!
