### ISSUE TITLE
Incorrect naming convention for serialized objects

### ISSUE THREAD

**Issue by tomajar** [developerforce/Force.com-Toolkit-for-NET#104]
There are lot of DTO objects, for the json serialization that do not match proper naming convention like:
* should start with upper case
* no unerscroces in properties name

The example of such object is:
```cs
 public class AuthToken
    {
        public string id;
        public string issued_at;
        public string instance_url;
        public string signature;
        public string access_token;
        public string refresh_token;
    }
```

In my opinion it should be like:

```cs
public class AuthToken
    {
		[JsonProperty(PropertyName = "id")]
        public string Id;

		[JsonProperty(PropertyName = "issued_at")]
        public string IssuedAt;

		[JsonProperty(PropertyName = "instance_url")]
        public string InstanceUrl;

		[JsonProperty(PropertyName = "signature")]
        public string Signature;

		[JsonProperty(PropertyName = "access_token")]
        public string AccessToken;

		[JsonProperty(PropertyName = "refresh_token")]
        public string RefreshToken;
    }
```

There are lot of objects like this - in the library, tests and samples.

In my opinion it's worth fixing, even if it's a build breaking change for others. The lower case properties with underscore looks unprofessinal.

I can try to contribute with the change if you like.

Thanks!

**Comment by wadewegner** [comment]
This is something I've wanted to address for awhile. I'll fix for our next major release.

**Comment by wadewegner** [comment]
It was a ton of work, but it's complete. https://github.com/developerforce/Force.com-Toolkit-for-NET/commit/8ff9da7c3e686a376498298e2aab5435caa6d9a0
