### ISSUE TITLE
Cleanup ServiceHttpClient responsibilities for querying objects

### ISSUE THREAD

**Issue by tomajar** [developerforce/Force.com-Toolkit-for-NET#106]
Hi @wadewegner 

In my opinion, the class

```cs
  public class ServiceHttpClient : IServiceHttpClient, IDisposable
```

Should have only the ability to raw communication, providing handy http methods, that takes object an some kind of form of urlSuffix.

So.. please remove method:

```cs
public async Task<IList<T>> HttpGetAsync<T>(string urlSuffix, string nodeName)
        {
```

It has wrong *responsibility* that doesn't match this class
* it appends the url with the *query/{0}* suffix
* it iterates over result items: *(jObject.GetValue("nextRecordsUrl")*

Do you remember, that there is an property inside of QueryResult class?

```cs
 public class QueryResult<T>
    {
        [JsonProperty(PropertyName = "nextRecordsUrl")]
        public string NextRecordsUrl { get; set; }
}
```

The Ability to iterate over collection should be inside:

```cs
public class ForceClient
{
  public Task<QueryResult<T>> QueryAsync<T>(string query, bool followNextRecordUrl = false)
        {
```

You can add new parameter to this metod: *bool followNextRecordUrl*

You will gain the ability to have *strongly typed* property, because you will don't have to use jObject.GetValue("nextRecordsUrl") but queryResult.NextRecordsUrl.

I think you can write the do...while method in ForceClient class.

When you will have a method with parameter *followNextRecordUrl*, none will need a method:

```cs
public class ForceClient
{
 public Task<QueryResult<T>> QueryContinuationAsync<T>(string nextRecordsUrl)
        {
```

Why? Because none will have to explicitly call it! 

Edit:

Ok, maybe it will be still useful if someone  want to iterate the results manually.

Anyway, I want to show you that HttpGetAsync(urlSuffix, nodeName) should not be there at all at the first place.

**Comment by wadewegner** [comment]
I hear you. Let me noodle on it a bit. Thank you!
