### ISSUE TITLE
IForceClient dispose method

### ISSUE THREAD

**Issue by tomajar** [developerforce/Force.com-Toolkit-for-NET#107]
Hi @wadewegner 

I'm just wondering..

```cs
 public interface IForceClient
    {
 // other methods
        void Dispose();
    }
```

Do you need your own dispose definition in here?

Can't it look like this?

```cs
 public interface IForceClient : IDisposable
    {
 // other methods
 //        void Dispose(); - inherited from IDisposable
    }
```

**Comment by tomajar** [comment]
The same question applies to:

```cs
 interface IAuthenticationClient
    {
   // ...
   void Dispose();
```
Maybe there are more interfaces like that.  I see the same in IServiceHttpClient.

Compare things like this:

```cs
using(AuthenticationClient aa = new AuthenticationClient())
{
// compiles
}

using (IAuthenticationClient aa = new AuthenticationClient())
{
// Error	...  type used in a using statement must be implicitly convertible to 'System.IDisposable' 
}
```

I'm not sure should the dispose method be in your main interfaces or not, but if it does, it should be inherited from IDisposable - do you agree?

**Comment by wadewegner** [comment]
Good spotting. The `Dispose` methods used to be used before significant refactoring last year (where we let you inject the `HttpClient`). Looks like this wasn't cleaned up. We'll address it.

**Comment by wadewegner** [comment]
Fixed: https://github.com/developerforce/Force.com-Toolkit-for-NET/commit/5bec98ead34b291a82478314e795000e8d567858
