### ISSUE TITLE
Add an option to retrieve IServiceHttpClient from IForceClient

### ISSUE THREAD

**Issue by tomajar** [developerforce/Force.com-Toolkit-for-NET#108]
Hi @wadewegner 

Currently, there is no way, to operate (GET, POST, etc.) on any resource based on retrieved link with ForceClient.

I want to write some self-discovery logic.  How to access resources by url that I don't know at runtime?

```javascript
  "urls": {
                "sobject": "/services/data/v32.0/sobjects/Account",
                "approvalLayouts": "/services/data/v32.0/sobjects/Account/describe/approvalLayouts",
                "quickActions": "/services/data/v32.0/sobjects/Account/quickActions",
                "describe": "/services/data/v32.0/sobjects/Account/describe",
                "listviews": "/services/data/v32.0/sobjects/Account/listviews",
                "rowTemplate": "/services/data/v32.0/sobjects/Account/{ID}",
                "layouts": "/services/data/v32.0/sobjects/Account/describe/layouts",
                "compactLayouts": "/services/data/v32.0/sobjects/Account/describe/compactLayouts"
            }
```

I was thinking on a scenrio, to provide acccess to the raw http client interface:

```cs
AuthenticationClient auth = new AuthenticationClient();

IForceClient forceClient = new ForceClient(auth.InstanceUrl, auth.AccessToken, auth.ApiVersion);
IServiceHttpClient serviceClient = forceClient.ServiceHttpClient;

var someObject = forceClient.QueryAsync<dynamic>("some query");

// 'someObject' contains a urls collection to follow like 'urls.quickActions'
var quickActionObject = serviceClient.HttpGetAsync<dynamic>(someObject.urls.quickActions);
```

Since it is a toolkit, it should allow to use raw http methods based on links provided with the objects. Since there are links like 'rowTemplate' in the urls collection i'm guessing that I should be able to POST a resource directly, etc.

The code will be very simple to change:

```cs
	public class ForceClient : IForceClient, IDisposable
	{
		private readonly ServiceHttpClient _serviceHttpClient;

		public IServiceHttpClient ServiceHttpClient
		{
			get { return _serviceHttpClient; }
		}

		// ...
	}
```

And an interface 

```cs
public interface IForceClient
	{
		IServiceHttpClient ServiceHttpClient { get; }
		\\ ...
	}
```

Can you please add this? I think it's quite easy and does not require any test.

note: I know that it requires new property in interface: IForceClient.ServiceHttpClient, maybe you have better idea for interface segregation. 

Can you add this?

**Comment by wadewegner** [comment]
It's an interesting idea! I like it. We'll review and consider. Thank you!
