### ISSUE TITLE
Extra samples, regarding upserting with external IDs in Lookups

### ISSUE THREAD

**Issue by willemmulder** [developerforce/Force.com-Toolkit-for-NET#109]
I'd love to see extra examples with upserts.

Specifically with using external ids on the upserted record, AND using an external Id for a related record in a lookup field on the upserted record.

Could that be done?

**Comment by dcarroll** [comment]
Hi Willem, will definitely take a look at adding more samples.

On Wed, Apr 29, 2015 at 7:11 AM, Willem Mulder <notifications@github.com>
wrote:

> I'd love to see extra examples with upserts.
>
> Specifically with using external ids on the upserted record, AND using an
> external Id for a related record in a lookup field on the upserted record.
>
> Could that be done?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/developerforce/Force.com-Toolkit-for-NET/issues/109>.
>



-- 
Thanks,
Dave

**Comment by wadewegner** [comment]
There are a lot of examples in the functional tests: https://github.com/developerforce/Force.com-Toolkit-for-NET/blob/master/src/ForceToolkitForNET.FunctionalTests/ForceClientTests.cs#L443

**Comment by willemmulder** [comment]
@dcarroll Thanks! 

Just a simple example would already be great, so people don't have to go into the test files to see whether/how upsert is supported. 

A quick questions: is using an external Id for a related record in a lookup field on the upserted record supported?

I.e. what's usually possible (pseudo-code)

someContact.Account = new Account(External_id = 1234);
upsert someContact;

And then the someContact.AccountId will be filled with the proper Account. Is this supported with the .NET package?

**Comment by wadewegner** [comment]
This shows how to use `UpsertExternalAsync` to update with an external Id: https://github.com/developerforce/Force.com-Toolkit-for-NET/blob/master/src/ForceToolkitForNET.FunctionalTests/ForceClientTests.cs#L475

**Comment by willemmulder** [comment]
Hi @wadewegner thanks.

Just as a suggestion: I think some real documentation of the features, including examples would be beneficial for many people; digging through the tests is not the same.
