### ISSUE TITLE
Missing issued_at and signature during login

### ISSUE THREAD

**Issue by tomajar** [developerforce/Force.com-Toolkit-for-NET#110]
Hi @wadewegner 

Everyone somtimes wonder, when AccessToken expires.

Now I've found this: [https://www.salesforce.com/us/developer/docs/api_rest/Content/intro_understanding_refresh_token_oauth.htm]

> The session timeout for an access token can be configured in Salesforce from Setup by clicking Security Controls | Session Settings.

> If the application uses the username-password OAuth authentication flow, no refresh token is issued, as the user cannot authorize the application in this flow. If the access token expires, the application using username-password OAuth flow must re-authenticate the user.

Can you please add new properties to AuthenticationClient and fill them up?

I think that the workflow like:
* session will expire in 2h*
* I'll re-login in after about 1h 55m
* get new token for 2h*

* 2h - is an example, this can be from 15min to 2h range.

Could be quite optimal and safe. Otherwise it's quite hard to manage auth-failures in the application. Especially, with Streaming API (there is no example :/ - do you know any?)

Note: I don't quite get when the refresh_token is filled up during login. I didn't saw any sample for that, so maybe I'll figure this out or rasie some bug. But for now, I think that you should fill-up all possible data that you get during login so anyone can use for it's own workflow.

Thanks!

**Comment by dcarroll** [comment]
Because you can't know when the token will expire, the recommended pattern
is to "handle" the expired token as an expected exception, refresh the
token (either using the refresh token, or re-doing the username password
auth) and then retry the operation that was in flight when the expired
token was discovered.  Other approaches will result in more problems than
solutions.


On Thu, Apr 30, 2015 at 8:31 AM, tomajar <notifications@github.com> wrote:

> Hi @wadewegner <https://github.com/wadewegner>
>
> Everyone somtimes wonder, when AccessToken expires.
>
> Now I've found this: [
> https://www.salesforce.com/us/developer/docs/api_rest/Content/intro_understanding_refresh_token_oauth.htm
> ]
>
> The session timeout for an access token can be configured in Salesforce
> from Setup by clicking Security Controls | Session Settings.
>
> If the application uses the username-password OAuth authentication flow,
> no refresh token is issued, as the user cannot authorize the application in
> this flow. If the access token expires, the application using
> username-password OAuth flow must re-authenticate the user.
>
> Can you please add new properties to AuthenticationClient and fill them up?
>
> I think that the workflow like:
>
>    - session will expire in 2h*
>    - I'll re-login in after about 1h 55m
>    -
>
>    get new token for 2h*
>    -
>
>    2h - is an example, this can be from 15min to 2h range.
>
> Could be quite optimal and safe. Otherwise it's quite hard to manage
> auth-failures in the application. Especially, with Streaming API (there is
> no example :/ - do you know any?)
>
> Note: I don't quite get when the refresh_token is filled up during login.
> I didn't saw any sample for that, so maybe I'll figure this out or rasie
> some bug. But for now, I think that you should fill-up all possible data
> that you get during login so anyone can use for it's own workflow.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/developerforce/Force.com-Toolkit-for-NET/issues/110>.
>



-- 
Thanks,
Dave

**Comment by wadewegner** [comment]
Closing. If there's anything actionable, please feel free to re-open with more details.
