### ISSUE TITLE
HttpGetAsync functions return cached results when run on Windows Phone 8.1

### ISSUE THREAD

**Issue by jhorst11** [developerforce/Force.com-Toolkit-for-NET#112]
Windows phone does auto caching if it detects the same network call more than once. So executing the same SOQL query will return cached results even if there was a change on the server side.

Adding the following before calls when running on Windows Phone fixes this:

request.Headers.IfModifiedSince = new DateTimeOffset(DateTime.Now);

**Comment by wadewegner** [comment]
Good to know. Did you want to submit a pull request with this addition?

Anyone see any reason why adding this globally would be problematic?

**Comment by tomajar** [comment]
In theory - adding this globally would never return data. Since my client implementation does not have cache like Windows Phone, I would never see old data?

Maybe it would be better to expose somehow http request, because now there is only http client injected in constructor?

that's my guess.

**Comment by wadewegner** [comment]
Closing this. If it's something we should still consider please let me know and we can take a look.
