### ISSUE TITLE
HardCoded APIVersion set to version 32 in AuthenticationClient.cs

### ISSUE THREAD

**Issue by saramorgan** [developerforce/Force.com-Toolkit-for-NET#113]
I am working on code for the DEV502 class and part of the exercise we use, returns the API version of the authenticated client and displays it to the console. I happened to notice in some recent testing that the version passed back was 32 and not 34 as it should be currently. In a search of the code in this repository, I found the following code in src/commonLibrariesForNET/AuthenticationClient.cs:

public string RefreshToken { get; set; }
15	        public string Id { get; set; }
16	        public string ApiVersion { get; set; }
…	
29	            if (httpClient == null) throw new ArgumentNullException("httpClient");
30	
31	            _httpClient = httpClient;
32	            ApiVersion = "v32.0";
33	        }

It looks like the apiversion has been hardcoded and should probably be changed to be whatever the current version is ( I would assume).

**Comment by wadewegner** [comment]
Thanks @saramorgan! This is indeed purposeful. The SDK is designed to make it easy for you to change the API version yourself programmatically but defaults to the last knowing working API version. That's not to say it won't work with v34, only we haven't tested it. Hope this helps!

**Comment by saramorgan** [comment]
AH, that makes sense and we can make sure the students are aware of this. THANKS for getting back to me so quickly, btw. I am way impressed by you....:-)All the best,SaraOn May 4, 2015 at 3:06 PM Wade Wegner <notifications@github.com> wrote:Thanks @saramorgan! This is indeed purposeful. The SDK is designed to make it easy for you to change the API version yourself programmatically but defaults to the last knowing working API version. That's not to say it won't work with v34, only we haven't tested it. Hope this helps!—Reply to this email directly or view it on GitHub.  Sara Morgan NettlesIndependent Software Developer and Professional AuthorMy Blog: www.saramorgan.netMy Linked In Profile: https://www.linkedin.com/in/sarahasnolimits

**Comment by saramorgan** [comment]
FYI. In case anyone else encounters this issue and wonders how to set the APIVersion and whether it will work with API version 34, I have tested and it will (at least testing with the simple console app). Setting the version is dead simple too (just pass in the version after authenticating when you create an instance of the ForceClient. Like this:

var client = new ForceClient(auth.InstanceUrl, auth.AccessToken, "v34.0");
