### ISSUE TITLE
Error with authentication

### ISSUE THREAD

**Issue by sofietkindt** [developerforce/Force.com-Toolkit-for-NET#115]
Hi,

I have tried to authenticate with Salesforce in .NET first in a MVC app, then in a simple console application, but it just doesn't work. I always get this error "An unhandled exception of type 'System.AggregateException' occurred in mscorlib.dll" when calling UsernamePasswordAsync:

var auth = new AuthenticationClient();
await auth.UsernamePasswordAsync(clientId, clientSecret, username, password);

Any ideas why? Did I setup my connected app wrong in Salesforce? The callback url, is that important?

Thank you very much for your help!!!
Sofie

**Comment by wadewegner** [comment]
Take a look at the details in your `AggregateException`. http://codeblog.jonskeet.uk/2011/06/22/eduasync-part-11-more-sophisticated-but-lossy-exception-handling/

**Comment by wadewegner** [comment]
Going to close. If you find additional information to share, please feel free to re-open.
