### ISSUE TITLE
Formatting URL for refresh token 

### ISSUE THREAD

**Issue by pousta** [developerforce/Force.com-Toolkit-for-NET#116]
Hi,
I recently upgrade your package to version 1.0.0 from NuGet. I believe there is a bug when you format url for refresh token request.

This is the request as captured by fiddler:
/services/oauth2/token?grant_type=RefreshToken&client_id={clientId}&RefreshToken={refreshToken}

I believe that value of grant_type parameter should be "refresh_token" instead of RefreshToken and also parameter name "RefreshToken" should be refresh_token.
/services/oauth2/token?grant_type=refresh_token&client_id={clientId}&refresh_token={refreshToken}

Best,
Jan

**Comment by brooksyott** [comment]
I've experienced the same issue. I made the following change to have the refresh tokens working again:

In Common.cs

        public static string FormatRefreshTokenUrl(
            string tokenRefreshUrl,
            string clientId,
            string refreshToken,
            string clientSecret = "")
        {
            if (tokenRefreshUrl == null) throw new ArgumentNullException("tokenRefreshUrl");
            if (clientId == null) throw new ArgumentNullException("clientId");
            if (refreshToken == null) throw new ArgumentNullException("refreshToken");

            var clientSecretQuerystring = "";
            if (!string.IsNullOrEmpty(clientSecret))
            {
                clientSecretQuerystring = string.Format("&client_secret={0}", clientSecret);
            }

            var url =
            string.Format(
                "{0}?grant_type=refresh_token&client_id={1}{2}&refresh_token={3}",
                tokenRefreshUrl,
                clientId,
                clientSecretQuerystring,
                refreshToken);

            return url;
        }

**Comment by wadewegner** [comment]
This was fixed: https://github.com/developerforce/Force.com-Toolkit-for-NET/commit/0d2ce7cd9897572fc831b6101edbbbee5de88f20. In the process of pushing updates to NuGet.
