### ISSUE TITLE
Issue with build

### ISSUE THREAD

**Issue by wadewegner** [developerforce/Force.com-Toolkit-for-NET#118]
@dcarroll it looks like there may be something wrong with your setup - let's fix it, as it caused one of the automated builds to fail.

**Comment by dcarroll** [comment]
This should have been in a new branch

On Mon, Jun 15, 2015 at 4:04 PM, Wade Wegner <notifications@github.com>
wrote:

> Assigned #118
> <https://github.com/developerforce/Force.com-Toolkit-for-NET/issues/118>
> to @dcarroll <https://github.com/dcarroll>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/developerforce/Force.com-Toolkit-for-NET/issues/118#event-331560632>
> .
>



-- 
Thanks,
Dave

**Comment by dcarroll** [comment]
I commited to a new branch.  How does that muck the master?

**Comment by wadewegner** [comment]
Looks like it causes the CI services to fire. I'll look into it. Thanks!

**Comment by wadewegner** [comment]
Working.
