### ISSUE TITLE
Change chatter group feed unit test

### ISSUE THREAD

**Issue by wadewegner** [developerforce/Force.com-Toolkit-for-NET#119]
Commit: https://github.com/developerforce/Force.com-Toolkit-for-NET/commit/1bfc55403b81c6f29be67bc245539002d01edef4

I understand the intention here. I probably wrote the test poorly - I'd resolve the failed unit test by creating feed data on a group in the developer org used for testing. The problem is that this will almost never get tested, as there aren't groups nor feeds in the groups by default. Instead of performing a count, I'd suggest we create a feed on a group instead - that way the condition always exists and we can test for it.

/cc @dcarroll

**Comment by devangel** [comment]
Sounds reasonable. A bigger problem is having the credentials to the org in test code.  Anyone could wack the feed the group and just about anything else.  Having said that, I don't think there is a good way to have a secure testing org where the credentials are protected.

**Comment by wadewegner** [comment]
2FA on the creds. So far no problems. =)

It is actually possible with both of the CI services. I just haven't had any need (yet) to enable.

**Comment by dcarroll** [comment]
So, you added 2FA to the test user?

**Comment by wadewegner** [comment]
It's been that way since the very beginning.

**Comment by wadewegner** [comment]
Nothing to see here any longer ...
