### ISSUE TITLE
QueryAsync Expects a Type

### ISSUE THREAD

**Issue by tmowbrey** [developerforce/Force.com-Toolkit-for-NET#120]
When completing the following statement:

var result = await client.QueryAsync(queryString);

I am receiving the following error: The type arguments for method "Salesforce.Force.ForceClientAsync<T>(string)" cannot be inferred from the usage. Try specifying the type arguments explicitly.

I was hoping that I could dynamically query without specifying a type much like I can do with native Apex and return an SObject. Is this possible or does everything have to be strongly typed?

**Comment by tmowbrey** [comment]
Nevermind, got this figured out. Needed to use the dynamic keyword. Ended up with code looking like the following:

var queryString = queryInput.Text;
var results = await client.QueryAsync<dynamic>(queryString);
foreach(dynamic obj in (dynamic)results)
{
messageBox.Text = obj;
}

**Comment by pousta** [comment]
I think this would work too:
var results = await client.QueryAsync<dynamic>(queryString);

**Comment by tmowbrey** [comment]
Thanks for the update but unfortunately, as my original comment outlined, that statement does not work. I'm using the toolkit in a windows app which may be the issue, I'm not sure, but QueryAsync requires a type.
