### ISSUE TITLE
Better Url formatting 

### ISSUE THREAD

**Issue by natelowry** [developerforce/Force.com-Toolkit-for-NET#125]
I spent a couple hours trying to debug an issue with any API call which ended up being caused by passing the trailing `/` in my `instanceUrl`.  It created a double `/` in my request Url which broke everything :/
`https://na31.salesforce.com//services/data/v29.0/query?q=...`

This could be avoided by using the `Uri` constructor instead of just `string.Format` like this:
```C#
public static string FormatUrl(string resourceName, string instanceUrl, string 
{
    ...
    var uri = new Uri(new Uri(instanceUrl), 
        string.Format("/services/data/{0}/{1}", apiVersion, resourceName));
    return uri.ToString();
}
```

If anyone else has run into this issue or just thinks it's a good idea, :+1: this and I'll put together a PR

**Comment by wadewegner** [comment]
Would greatly appreciate a pull request! Would you first add a failing test and confirm your change fixes. Thanks!

**Comment by wadewegner** [comment]
Done! Thanks for the suggestion. I updated to actually return the `Uri` instead of string and made updates accordingly.

**Comment by wadewegner** [comment]
Here are the commits: https://github.com/developerforce/Force.com-Toolkit-for-NET/commit/8599322dc85663c16a869e7aec09b6e469edf415 & https://github.com/developerforce/Force.com-Toolkit-for-NET/commit/c9c54b715073c2e9291c8b395afe75d3aee8850a
