### ISSUE TITLE
Latest REST API version support

### ISSUE THREAD

**Issue by sushantjadhav21** [developerforce/Force.com-Toolkit-for-NET#129]
I guess the latest chatter REST API version is "v34.0" and .NET SDK is still using targeting the "v30.0". I am just checking when you are planning to update the .NET SDK to support the latest version of Chatter REST API.

**Comment by saramorgan** [comment]
Hi,

The Api version is set by default to 30, but you can change it yourself to the latest version very easily. Check out this post which I did about the issue.  http://saramorgan.net/2015/05/05/heads-up-how-to-set-the-api-version-using-the-force-com-toolkit-for-net/

**Comment by wadewegner** [comment]
Some of the latest commits by @dcarroll have updated to v34. We'll have this updated in the next release of the NuGet.
