### ISSUE TITLE
Calling custom REST services

### ISSUE THREAD

**Issue by jneavegit** [developerforce/Force.com-Toolkit-for-NET#130]
We can't get the toolkit working with a custom REST service we have. It seems to be building the URL incorrectly. The service is named "GetDirectDebitTransactions". Some details:

The code snippet:

using (var eftTypesTask = sfConnector.ExecuteRestApi<Transaction>("GetDirectDebitTransactions", "?StartDate=01/05/2015&EndDate=30/06/2015"))

Instead of going to this address: https://cs6.salesforce.com/services/apexrest/GetDirectDebitTransactions
It goes to the following: https://cs6.salesforce.com/services/data/v32.0/https://cs6.salesforce.com/services/apexrest/GetDirectDebitTransactions

Any ideas? Thanks.

**Comment by wadewegner** [comment]
This has been fixed as part of this pull request: https://github.com/developerforce/Force.com-Toolkit-for-NET/pull/131

It should make it into the next NuGet package.

**Comment by saramorgan** [comment]
Wade,Do you know when the next NuGet package is scheduled to be released? I was going to do a post about it and highlight some of the bigger fixes/enhancements from this latest round you have been on. And on behalf of Salesforce Developers, thank you for all you have done to support this release.Best,SaraOn August 26, 2015 at 3:51 PM Wade Wegner <notifications@github.com> wrote:This has been fixed as part of this pull request: #131It should make it into the next NuGet package.—Reply to this email directly or view it on GitHub.  Sara Morgan NettlesIndependent Software Developer and Professional AuthorMy Blog: www.saramorgan.netMy Linked In Profile: https://www.linkedin.com/in/sarahasnolimits

**Comment by wadewegner** [comment]
I'm training @dcarroll on how to publish <grin> and he's agreed to publish next. Dave, think you could do this today and publish as 1.1.1?

**Comment by dcarroll** [comment]
easy peasy, is everything we want in there in there?


On Wed, Aug 26, 2015 at 2:00 PM, Wade Wegner <notifications@github.com>
wrote:

> I'm training @dcarroll <https://github.com/dcarroll> on how to publish
> and he's agreed to publish next. Dave, think you could do this today and
> publish as 1.1.1?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/developerforce/Force.com-Toolkit-for-NET/issues/130#issuecomment-135168975>
> .
>



-- 
Thanks,
Dave

**Comment by wadewegner** [comment]
I'd like to get https://github.com/developerforce/Force.com-Toolkit-for-NET/pull/121 in there too. Let's make a call later today.

**Comment by dcarroll** [comment]
Ok, if that's the case, tomorrow is when I can push to nuget.

On Wed, Aug 26, 2015 at 2:14 PM, Wade Wegner <notifications@github.com>
wrote:

> I'd like to get #121
> <https://github.com/developerforce/Force.com-Toolkit-for-NET/pull/121> in
> there too. Let's make a call later today.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/developerforce/Force.com-Toolkit-for-NET/issues/130#issuecomment-135172217>
> .
>



-- 
Thanks,
Dave

**Comment by bluephlame** [comment]
I"m not sure if this is intentional but the nuGet package that was published yesterday did not have the most up todate DLL in it. Are you still looking at doing another push up to nuGet.

**Comment by wadewegner** [comment]
The repo always will be slightly ahead of the NuGet. What specifically do you see missing?

(I'm not by a PC to easily check. I tested last night but it's possible I missed something. Hope not!)

**Comment by bluephlame** [comment]
IT appears that Nuget Package v1.1.0 only has the DLL version 1.0.0 so it is missing all the recent changes. including #131 Which is the one we need.

**Comment by wadewegner** [comment]
The assembly will *always* stay version 1.0.0 so we never force people to deal with assembly binding redirects.

I haven't pushed an update to NuGet since committing the changes you reference. We can do that today.

**Comment by wadewegner** [comment]
@dcarroll just pushed 1.1.1 with these updates. @bluephlame please give it a try!
