### ISSUE TITLE
Consider unifying return values of CreateAsync and UpdateAsync

### ISSUE THREAD

**Issue by Krizzzn** [developerforce/Force.com-Toolkit-for-NET#132]
For the next set of breaking changes I'd like to propose that `CreateAsync` and `UpdateAsync` both should return a `SuccessResponse` instead of `string` and `SuccessResponse`. 

If the idea gets accepted I could provide a pull request.

**Comment by wadewegner** [comment]
Geez. Great point. I don't know why I originally built `CreateAsync` to only return the `Id` string. I will take a look at resolving.

**Comment by wadewegner** [comment]
I have committed a fix. https://github.com/developerforce/Force.com-Toolkit-for-NET/commit/f0873750aef2f704b868eb8b3c216027be98d6f8

Although minor, it is a breaking change. We'll have to think through the strategy for release.
