### ISSUE TITLE
Use Force toolkit as salesforce api client

### ISSUE THREAD

**Issue by pawepaw** [developerforce/Force.com-Toolkit-for-NET#133]
I've faced some problems using your nuget. I got error 
```The type 'System.Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime ```

I understand that if i created dll with salesforce api client using your nuget I have to reference:
 ``` <package id="Microsoft.Bcl" version="1.1.10" targetFramework="net45" />```

In all projects that include dll with salesforce api?

**Comment by wadewegner** [comment]
Can you provide a way to reproduce the behavior we can test? My guess is you have a mismatch of assemblies referenced.

**Comment by pawepaw** [comment]
I can try to provide something. But from http://blogs.msdn.com/b/bclteam/archive/2013/04/17/microsoft-bcl-async-is-now-stable.aspx documentation i see that i have to reference in every project to make it working and i see that you include it in every sample and test application.

**Comment by pawepaw** [comment]
I can reproduce it only on my build server (teamcity). On local machine it works fine. I have microsoft.bcl packages referenced in project but still get this error. Is it possible that I am missing some sdk or something on my build server?

**Comment by peranborkett** [comment]
Have you tried referencing the 'Facade' dll

C:\Program Files (x86)\Reference
Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.ObjectModel.dll

Change the path to suit the your version of the framework.


Regards

Peran

**Comment by wadewegner** [comment]
I'm going to close this issue. If you can provide more details or a sample we can use to better diagnose, please feel free to re-open.
