### ISSUE TITLE
Deserialization when using Address type

### ISSUE THREAD

**Issue by nloding** [developerforce/Force.com-Toolkit-for-NET#138]
I am trying to insert a new Person Account. The insertion works except for the Mailing Address field (PersonMailingAddress), which generates the following exception:

`{"Cannot deserialize instance of PersonMailingAddress from VALUE_STRING value Royal Oak at [line:1, column:113]"}`

`PersonMailingAddress` is a property on my model that I'm inserting. "Royal Oak" is the value of the city field. I've tried it with various different values, with/without spaces, all generate this same error. Since this is a compound field, I created a separate class for it, called `Address`:

    public class Address
    {
        [JsonProperty(PropertyName = "City")]
        public string MailingCity { get; set; }

        [JsonProperty(PropertyName = "Country")]
        public string MailingCountry { get; set; }

        [JsonProperty(PropertyName = "PostalCode")]
        public string MailingPostalCode { get; set; }

        [JsonProperty(PropertyName = "State")]
        public string MailingState { get; set; }

        [JsonProperty(PropertyName = "Street")]
        public string MailingStreet { get; set; }
    }

The values are set then pushed up using `CreateAsync` and that's when this error returns. If I leave the PersonMailingAddress field off my model it inserts just fine. (As a side note, this Address object works when inserting a Contact, it seems to just be the Account/Person Account that it has trouble with.)

Any thoughts as to how I should get this to insert properly?

**Comment by nloding** [comment]
Found my answer in a SFDC forum. Thanks!

http://salesforce.stackexchange.com/a/89565/24243

**Comment by dcarroll** [comment]
I had an inkling there was some special handling on the SFDC side for
person acccounts.

:-)

On Thu, Aug 27, 2015 at 12:41 PM, Nathan Loding <notifications@github.com>
wrote:

> Closed #138
> <https://github.com/developerforce/Force.com-Toolkit-for-NET/issues/138>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/developerforce/Force.com-Toolkit-for-NET/issues/138#event-394389643>
> .
>



-- 
Thanks,
Dave
