### ISSUE TITLE
Unable to Login from Windows Emulator and Windows Phone

### ISSUE THREAD

**Issue by meenanarendra** [developerforce/Force.com-Toolkit-for-NET#139]
Hi,

We are able to login to RHPlay and SIT2 environment, when we run UsernamePasswordAsync method from console application. We have used the similar implementation for Xamarin application that is running on windows Emulator or windows phone. The same code gives error as shown in below snapshot.
![image](https://cloud.githubusercontent.com/assets/7714896/9649495/5fb41646-51bb-11e5-9540-01d671d5ff9c.png)

Here is the code implementation.
![image](https://cloud.githubusercontent.com/assets/7714896/9649501/732fd6e2-51bb-11e5-80f9-0b62a33b3fe0.png)

Please suggest.

**Comment by wadewegner** [comment]
Can you run a Fiddler trace and share the exact response from Salesforce?

**Comment by meenanarendra** [comment]
Hi Wade,

Thank You for replying. This was due to our network settings. I have
disconnected from VPN and run the emulator. it works for me.

Thank You
Narendra

On Mon, Sep 7, 2015 at 11:22 AM, Wade Wegner <notifications@github.com>
wrote:

> Can you run a Fiddler trace and share the exact response from Salesforce?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/developerforce/Force.com-Toolkit-for-NET/issues/139#issuecomment-138335030>
> .
>



-- 
Thanks & Regards,
Narendra K Meena
502-994-4825
