### ISSUE TITLE
LeadSource field required when updating Lead

### ISSUE THREAD

**Issue by ivanschwarz** [developerforce/Force.com-Toolkit-for-NET#144]
Thank you for this toolkit, it looks very promising!

Currently I'm running into this issue:
When I try to update a Lead, I get a ForceException: "You have to specify a Lead Source before continuing". Is this a correct behaviour? I don't want to overwrite a current value of a Lead Source field. With WSDL-generated reference, Lead Source is not required for a Update request.

**Comment by wadewegner** [comment]
Can you share your code so I can try to reproduce?

Apologies for the belated reply. I'm going to close this for now. If you're still having this issue, please re-open.
