### ISSUE TITLE
DateTime formatting

### ISSUE THREAD

**Issue by twhitbeck** [developerforce/Force.com-Toolkit-for-NET#146]
If I have a record with a `DateTime` field with `Kind`: `Local`, then when this gets serialized the standard date format "s" is used which doesn't include any timezone information.
see https://msdn.microsoft.com/en-us/library/az4se3k1(v=vs.110).aspx#Sortable

This leads to the date being set as UTC in Salesforce.
The format is specified [here](https://github.com/developerforce/Force.com-Toolkit-for-NET/blob/5c391b30606569f18169d0cc4cd28d6fdaf6f404/src/CommonLibrariesForNET/ServiceHttpClient.cs#L18)

Wouldn't it make more sense to use the Round-trip format "o"?

**Comment by wadewegner** [comment]
This is related to the following unit test: https://github.com/developerforce/Force.com-Toolkit-for-NET/blob/master/src/ForceToolkitForNET.FunctionalTests/ForceClientTests.cs#L611

When I set `DateFormat` to `o` this is the trace:

REQUEST:
```
POST https://na10.salesforce.com/services/data/v34.0/sobjects/Event HTTP/1.1
Accept: application/json
User-Agent: forcedotcom-toolkit-dotnet/v34.0
Authorization: Bearer TRIMMED
Accept-Encoding: gzip
Content-Type: application/json; charset=utf-8
Host: na10.salesforce.com
Cookie: BrowserId=pBayEdEJR0GGxmNkkLVrpg
Content-Length: 208
Expect: 100-continue

{"Description":"new Event","Subject":"new Event","WhatId":"001F000001fdP8tIAE","ActivityDate":"2016-01-16T11:44:17.0463124-08:00","ActivityDateTime":"2016-01-16T11:44:17.0473145-08:00","DurationInMinutes":10}
```

RESPONSE:
```
HTTP/1.1 400 Bad Request
Date: Sat, 16 Jan 2016 19:44:10 GMT
Sforce-Limit-Info: api-usage=546/15000
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked

A4
[{"message":"Cannot deserialize instance of date from VALUE_STRING value 2016-01-16T11:44:17.0463124-08:00 at [line:1, column:79]","errorCode":"JSON_PARSER_ERROR"}]
0
```

Whereas, when the `DateFormat` is set to `s` this REQUEST has no issues:

```
POST https://na10.salesforce.com/services/data/v34.0/sobjects/Event HTTP/1.1
Accept: application/json
User-Agent: forcedotcom-toolkit-dotnet/v34.0
Authorization: Bearer 00DF00000008H5t!ARgAQJmkXV_tB.UwjZ.Xvn92.5ekME330dnUHHrr7J1kgKKRdrToDA7TOTdzih7AKxJnc3OwRUvXF60u9e1cTZ0k4EHUJ1Rz
Accept-Encoding: gzip
Content-Type: application/json; charset=utf-8
Host: na10.salesforce.com
Cookie: BrowserId=uUPEvreaQ5iGsshNGKsxCQ
Content-Length: 180
Expect: 100-continue

{"Description":"new Event","Subject":"new Event","WhatId":"001F000001fdP9NIAU","ActivityDate":"2016-01-16T11:47:16","ActivityDateTime":"2016-01-16T11:47:16","DurationInMinutes":10}
```

That's why I have it set this way. Perhaps @dcarroll or @metadaddy-sfdc can comment if I've missed something?

**Comment by metadaddy-sfdc** [comment]
Looks like we don't like JSON Dates with sub-millisecond precision. This works for me (or at least fails on the invalid cross reference ids):

    {"Description":"new Event","Subject":"new Event","WhatId":"001F000001fdP8tIAE","ActivityDate":"2016-01-16T11:44:17.046-08:00","ActivityDateTime":"2016-01-16T11:44:17.047-08:00","DurationInMinutes":10}

Is there a format with precision limited to milliseconds?

**Comment by advancedrei** [comment]
When I craft SELECT statements using this library that use WHERE and GROUP BY clauses based on dates, I've found that I have to set the DateFormat to "s", and append a "Z" to the end of the string. That is the *ONLY* way the query will work. Your INSERTS may be OK with the "s" format without a Z, but Salesforce is definitely not OK with SELECTS being that way.

I don't have the foggiest idea how to get JSON.NET to do that, though.

**Comment by wadewegner** [comment]
Is this still an issue? Please re-open if so.
