### ISSUE TITLE
3rd Party SAML bearer 

### ISSUE THREAD

**Issue by jeanfrancoislarente** [developerforce/Force.com-Toolkit-for-NET#147]
I'm wondering if you were planning on adding support for SAML Bearer Assertion to the library? The method would basically take only the SAML Assertion and return the token?

Thanks very much.
J.F.

**Comment by dcarroll** [comment]
Will look into this.

On Wed, Oct 7, 2015 at 8:58 AM, jflarente <notifications@github.com> wrote:

> I'm wondering if you were planning on adding support for SAML Bearer
> Assertion to the library? The method would basically take only the SAML
> Assertion and return the token?
>
> Thanks very much.
> J.F.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/developerforce/Force.com-Toolkit-for-NET/issues/147>.
>



-- 
Thanks,
Dave

**Comment by wadewegner** [comment]
@jflarente Do you have any code you can share? I'm happy to explore adding it. If I have to start from scratch, it'll take a bit longer. ;-)

**Comment by wadewegner** [comment]
Is this still an issue? Please re-open if so.
