### ISSUE TITLE
AuthenticationClient returns just ApiVersion

### ISSUE THREAD

**Issue by DomCotton** [developerforce/Force.com-Toolkit-for-NET#148]
Hi,

I am new to oauth, salesforce, in fact i am new to this entire environment!  Up until today i have been working with a tool called "Office Toolkit for Salesforce" using an old com dll.  I want to move over to use the Rest API framework (please excuse any of my incorrect terminology).

I am following an example showing that i can authenticate and then create a new "ForceClient" - here is my code:

string consumerKey = "xxxxxxxxxxxxxxxxxxxxxxxxxxxx";
            string consumerSecret = "xxxxxxxxxxxxxxxxxxxxxx";
            string callbackUrl = "https://test.salesforce.com/services/oath2/callback";
            string password = "xxxxxxxxxxxxxxxxxxxxxxxxxx";

            var auth = new AuthenticationClient();
            var url = "https://test.salesforce.com/services/oath2/token";
            auth.UsernamePasswordAsync(consumerKey, consumerSecret, "user@domain.com.test101", password);

            var client = new ForceClient(auth.InstanceUrl, auth.AccessToken, auth.ApiVersion);

the "auth" object only comes back with an ApiVersion, but i get no errors.  Can anybody help me understand what is going on here?

Thanks,
Dom

**Comment by ivanschwarz** [comment]
Hello,

It seems you don't wait until the UsernamePasswordAsync is finished.

From Readme.md:
```bash
var auth = new AuthenticationClient();
await auth.UsernamePasswordAsync("YOURCONSUMERKEY", "YOURCONSUMERSECRET", "YOURUSERNAME", "YOURPASSWORD");
```

Note *await* keyword.

**Comment by DomCotton** [comment]
Hi,

Thanks for the speedy response, at least i now get an error!  Something to work with...

Regards,
Dom
