### ISSUE TITLE
Help to parse subquery results

### ISSUE THREAD

**Issue by acccollin** [developerforce/Force.com-Toolkit-for-NET#149]
Hello Forum,

I am running the following test query:

![image](https://cloud.githubusercontent.com/assets/6392702/10436156/ab076570-70f2-11e5-9c05-14f744cf17a0.png)

Could somebody share same examples on how to parse subquery results, i.e. in the query above CaseComments and EmailMessages?

results.records gives me access to the parent data, but I'm just trying to reach out to the two child objects of the query.

Thanks in advance!

**Comment by dcarroll** [comment]
The child objects should be wrapped in their own "queryResult" structure. The queryResult has a records array and a size and so on.

In your example it should be
`testResults.CaseComments.records[0].Name`

**Comment by acccollin** [comment]
Thanks for your reply Dave.

Got access to the child object - with just a few changes from the example you provided:
var testcomments = testResults.records[0].CaseComments.records;

**Comment by dcarroll** [comment]
Ah, yup, my bad.

On Mon, Oct 12, 2015 at 1:23 PM, acccollin <notifications@github.com> wrote:

> Closed #149
> <https://github.com/developerforce/Force.com-Toolkit-for-NET/issues/149>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/developerforce/Force.com-Toolkit-for-NET/issues/149#event-433329760>
> .
>



-- 
Thanks,
Dave
