### ISSUE TITLE
API_DISABLED_FOR_ORG error code is missing in Error enum

### ISSUE THREAD

**Issue by oleksii-iaroshchuk** [developerforce/Force.com-Toolkit-for-NET#150]
When I try to use any REST API method for GROUP or PROFESSIONAL account (for which API is disabled by default), I get the `ForceException` with Message="The REST API is not enabled for this Organization.", and Error=Unknown.
But if I peek at HTTP response, I see that body contains the following JSON:
```
[{"message":"The REST API is not enabled for this Organization.","errorCode":"API_DISABLED_FOR_ORG"}]
```
So, it seems like we have a specific code for this error returned from Salesforce, but it is not reflected in `Error` enum.

**Comment by wadewegner** [comment]
This was recently resolved: https://github.com/developerforce/Force.com-Toolkit-for-NET/blob/master/src/CommonLibrariesForNET/Models/Error.cs#L23
