### ISSUE TITLE
Web Server flow - get back username in AuthenticationClient

### ISSUE THREAD

**Issue by shankararunachalam** [developerforce/Force.com-Toolkit-for-NET#151]
We are replacing our Username-Password flow with the Web Server flow in a background process. We have two possible users who would use the process and so we want to ensure that we can persist their access and refresh tokens in a database against their usernames. 

I see that the AuthenticationClient only gives an Id field (salesforce-based) and not the username. Is it possible to add the username as well which is what our process would know?

**Comment by wadewegner** [comment]
My reading of the Web Server flow is that it doesn't return the username: https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_understanding_web_server_oauth_flow.htm.

@metadaddy-sfdc can confirm.

Using the `Id` field (which is a URL) you can then query it to get additional information, like the username. See: http://salesforce.stackexchange.com/a/11748

**Comment by metadaddy-sfdc** [comment]
Correct - OAuth response in web server flow does not include the username. See [Digging Deeper into OAuth 2.0 on Force.com](https://developer.salesforce.com/page/Digging_Deeper_into_OAuth_2.0_on_Force.com#Obtaining_an_Access_Token_in_a_Web_Application_.28Web_Server_Flow.29).
