### ISSUE TITLE
Unable to get assignment rule to fire or assign case to queue

### ISSUE THREAD

**Issue by pdandrea** [developerforce/Force.com-Toolkit-for-NET#153]
Steps taken:
1. var forceClient = new ForceClient(InstanceUrlSFDC, AccessTokenSFDC, ApiVersionSFDC);
2. var sfdcCase = new sfdcCase() {  ....elements added... }
3. var id = forceClient.CreateAsync(sfdcCase.SObjectTypeName, sfdcCase);
4. id.Wait();

The issue is, even though the case is successfully created, the assignment rule doesn't seem to fire and the case always end up in default queue.  I found in SOAP api something regarding AssignmentRuleHeader and assignementRuleId but don't see how to apply or use that with the REST ai and the toolkit.

Need to implement this functionality:

https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_header_assignmentruleheader.htm#kanchor423

https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_assignmentrule.htm

Perhaps a header can be added and it can be set before the execution of the create sync:
Sforce-Auto-Assign
https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/headers_autoassign.htm

Edit:
Further analysis revealed that actually the assignment rule does fire  every time but I can't turn it off with the toolkit do to none availability to use custom headers... with that ability I can explicitly assign ownership of a case.

**Comment by wadewegner** [comment]
You can create your `ForceClient` and inject the `HttpClient` with your own custom headers. Can you give this a try and let me know if you still have issues?

(Sorry for the belated reply.)
