### ISSUE TITLE
Could not load type '<HttpGetAsync>d__7`1' from assembly 'Salesforce.Common...

### ISSUE THREAD

**Issue by mreyeros** [developerforce/Force.com-Toolkit-for-NET#155]
I am seeing an issue on my end while using the toolkit. In my local development environment all works well, once deployed to one of our servers I receive the following error when attempting to get a list of records back from SF. The code I am calling looks like this:

 public async Task<List<CommunityContact>> GetCommunityContacts(string communityAccountId)
    {
        var auth = await Login();

        var client = new ForceClient(auth.InstanceUrl, auth.AccessToken, auth.ApiVersion);

        var query =
            "SELECT Id, Title, FirstName, LastName, Phone, Fax, Email, Active__c, Regional_Manager_Indicator__c " +
            "FROM contact " +
            "WHERE ID IN(SELECT contact__C " +
            "               FROM account_relationship__c " +
            "WHERE account__C = '" + communityAccountId + "')";

        var queryResults = await client.QueryAllAsync<CommunityContact>(query);

        return queryResults.Records;
    }
Could not load type 'd__7`1' from assembly 'Salesforce.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=9f7864e53fb79388' due to value type mismatch.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.TypeLoadException: Could not load type 'd__7`1' from assembly 'Salesforce.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=9f7864e53fb79388' due to value type mismatch.

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:

[TypeLoadException: Could not load type 'd__71' from assembly 'Salesforce.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=9f7864e53fb79388' due to value type mismatch.] Salesforce.Common.<HttpGetAsync>d__71.MoveNext() +0
System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start(TStateMachine& stateMachine) +70
System.Runtime.CompilerServices.AsyncTaskMethodBuilder1.Start(TStateMachine& stateMachine) +60 Salesforce.Common.ServiceHttpClient.HttpGetAsync(String urlSuffix) +295 Salesforce.Force.ForceClient.QueryAsync(String query) +267 MFH.Service.SalesForce.<GetCommunityContacts>d__e.MoveNext() in e:\Builds\39\ASP.PMSWebIT-Projects\mfh.assurant.com-dev\src\Multi Family Housing\MFH.Service\src\main\MFH.Service\SalesForce\SalesForceService.cs:67 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +59 System.Runtime.CompilerServices.TaskAwaiter1.GetResult() +25
mfh.assurant.com.Features.Community.d__0.MoveNext() in e:\Builds\39\ASP.PMSWebIT-Projects\mfh.assurant.com-dev\src\Multi Family Housing\mfh.assurant.com\src\dev\mfh.assurant.com\Features\Community\CommunityController.cs:30
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +59
System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult) +84
System.Web.Mvc.Async.<>c__DisplayClass37.b__36(IAsyncResult asyncResult) +17
System.Web.Mvc.Async.WrappedAsyncResult1.CallEndDelegate(IAsyncResult asyncResult) +10 System.Web.Mvc.Async.WrappedAsyncResultBase1.End() +49
System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +32
System.Web.Mvc.Async.AsyncInvocationWithFilters.b__3d() +50
System.Web.Mvc.Async.<>c__DisplayClass46.b__3f() +225
System.Web.Mvc.Async.<>c__DisplayClass46.b__3f() +225
System.Web.Mvc.Async.<>c__DisplayClass33.b__32(IAsyncResult asyncResult) +10
System.Web.Mvc.Async.WrappedAsyncResult1.CallEndDelegate(IAsyncResult asyncResult) +10 System.Web.Mvc.Async.WrappedAsyncResultBase1.End() +49
System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34
System.Web.Mvc.Async.<>c__DisplayClass2b.b__1c() +26
System.Web.Mvc.Async.<>c__DisplayClass21.b__1e(IAsyncResult asyncResult) +100
System.Web.Mvc.Async.WrappedAsyncResult1.CallEndDelegate(IAsyncResult asyncResult) +10 System.Web.Mvc.Async.WrappedAsyncResultBase1.End() +49
System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
System.Web.Mvc.Controller.b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +13
System.Web.Mvc.Async.WrappedAsyncVoid1.CallEndDelegate(IAsyncResult asyncResult) +36 System.Web.Mvc.Async.WrappedAsyncResultBase1.End() +54
System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +39
System.Web.Mvc.Controller.b__15(IAsyncResult asyncResult, Controller controller) +12
System.Web.Mvc.Async.WrappedAsyncVoid1.CallEndDelegate(IAsyncResult asyncResult) +28 System.Web.Mvc.Async.WrappedAsyncResultBase1.End() +54
System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +29
System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
System.Web.Mvc.MvcHandler.b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +21
System.Web.Mvc.Async.WrappedAsyncVoid1.CallEndDelegate(IAsyncResult asyncResult) +36 System.Web.Mvc.Async.WrappedAsyncResultBase1.End() +54
System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +31
System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
System.Web.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar) +129

**Comment by wadewegner** [comment]
Sounds like a serialization issue, most likely in your model `CommunityContact`. I'd recommend changing to `dynamic` and see if that works. From there, use Fiddler2 to capture the trace and take the JSON to http://json2csharp.com/ to generate the correct C# model.

Good luck!
