### ISSUE TITLE
Force.com Toolkit and TLS 1.0 deprecation 

### ISSUE THREAD

**Issue by acccollin** [developerforce/Force.com-Toolkit-for-NET#161]
Can you please confirm whether TLS 1.0 deprecation as per https://help.salesforce.com/HTViewSolution?id=000221207&language=en_US

would affect projects using the Force.com Toolkit?

**Comment by hyperoceanic** [comment]
I did some investigation yesterday with a colleague and yes it does seem to use TLS1.0. There are additionally issues when you change the security protocol before connecting:

`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;`

If you do that you get an error later - grant type not supported.

**Comment by wadewegner** [comment]
https://github.com/developerforce/Force.com-Toolkit-for-NET/issues/181

Sorry. I'm going to close this and track on the new issue.
