### ISSUE TITLE
can't build with Visual Studio 2015

### ISSUE THREAD

**Issue by bonhomie** [developerforce/Force.com-Toolkit-for-NET#162]
I opened the sample solution file within Community edition of visual studio 2015 and it has some issues restoring the nuget packages.
Severity	Code	Description	Project	File	Line
Error		This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets.	ForceToolkitForNET	C:\Project\salesforce\Force.com-Toolkit-for-NET\src\ForceToolkitForNET\ForceToolkitForNET.csproj	88

**Comment by wadewegner** [comment]
I had no issues opening the solution VS 2015 Professional Edition. For now I guess we don't support community edition. Apologies, I don't know the differences.

![image](https://cloud.githubusercontent.com/assets/746259/12373983/7e11d8e8-bc42-11e5-8b4e-1e742fac0f77.png)

**Comment by saramorgan** [comment]
@wadewegner and @bonhomie I have used the latest version of the Toolkit with the new Community version 2015 and had no problems. I think you just need to update your packages. Perhaps even remove them and re-add them.

**Comment by bonhomie** [comment]
Thanks, I managed to get it working on Community edition
