### ISSUE TITLE
Doesn't work with Newtonsoft.Json 8.0.1

### ISSUE THREAD

**Issue by AmbroiseCouissin** [developerforce/Force.com-Toolkit-for-NET#167]
I had a serialization bug when using latest newtonsoft.json version (8.0.1). I had to revert back to 7.0.1.

Here is the stack trace:

Unexpected character encountered while parsing value: t. Path 'done', line 3, position 11. ||| StackTrace:    at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)\r\n   at Newtonsoft.Json.JsonTextReader.ReadAsString()\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\r\n   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)\r\n   at Salesforce.Common.ServiceHttpClient.<HttpGetAsync>d__1`1.MoveNext()\r\n

**Comment by mattruma** [comment]
Running into this same problem.

**Comment by stuartajames** [comment]
+1 for a resolution to this issue

**Comment by benerdin** [comment]
I also just experienced this issue. No published version of the NuGet package was compatible with Newtonsoft.Json v8.0.1 when I tested today.

**Comment by wadewegner** [comment]
Thanks all. Looks like Newtonsoft.Json v8.0.1 just recently came out. I'll see if I can get it fixed soon.

**Comment by benerdin** [comment]
Thanks, Wade. I can't get the code to compile locally (it's complaining about "Window.props"), but here are some further findings:

In the classes <code>QueryResult</code> and <code>SuccessResponse</code>, the properties <code>QueryResult.Done</code> and <code>SuccessResponse.Success</code> are defined as type <code>string</code> but they are receiving a <code>bool</code> value from <code>JsonConvert.DeserializeObject</code>.

So, you're receiving **true** without quotes:
<pre>{ "done": true }</pre>

but you're expecting to get **"true"** with quotes:

<pre>{ "done": "true" }</pre>

Converting those properties to <code>bool</code> may fix the issue, but it could still be a conversion issue within the Newtonsoft.Json nuget package. I'm trying to verify that now.

Hope that helps!

**Comment by radleta** [comment]
I've created [a fork](https://github.com/radleta/Force.com-Toolkit-for-NET) with the necessary changes made which @benerdin refers to getting the library working with Newtonsoft.Json 8.0.1. We're working through trying to test to decide whether it'll be acceptable or not to use for us.

**Comment by wadewegner** [comment]
Sorry folks. Work/life got in the way. I'm address this today and will try to have updated packages soon.

**Comment by wadewegner** [comment]
Looks like Newtonsoft.Json 8.0.2 resolves some issues in 8.0.1 and I found 8.0.2 to work cleanly after updating. However, I think the changes from string to bool are good, and I'm going to apply them in this next build.

**Comment by wadewegner** [comment]
Here are the commits: https://github.com/developerforce/Force.com-Toolkit-for-NET/commit/2e9995e75c5f9c14dc0274ab6292ba26a04c7712 & https://github.com/developerforce/Force.com-Toolkit-for-NET/commit/7cfa752bf949eb02b82add7df325da9e334cffce

**Comment by wadewegner** [comment]
New packages available:

https://www.nuget.org/packages/DeveloperForce.Force/1.2.3
https://www.nuget.org/packages/DeveloperForce.Chatter/1.2.3

Thanks all! I'm closing this issue. Please let me know if you have any problems.
