### ISSUE TITLE
Read Only Properties

### ISSUE THREAD

**Issue by LiquidSean** [developerforce/Force.com-Toolkit-for-NET#170]
I am running into issues with read-only properties when serializing as they are not ignored when serializing to JSON. Perhaps a ContractResolver would solve this issue? . Also the serializer settings should be set to ignore nulls.

**Comment by wadewegner** [comment]
Can you share an example? I'm happy to look for a solution.

**Comment by LiquidSean** [comment]
{"Unable to create/update fields: LastModifiedDate, IsDeleted, IsConverted, LastViewedDate, LastReferencedDate, SystemModstamp, CreatedDate. Please check the security settings of this field and verify that it is read/write for your profile or permission set."}.  

I get responses similar to that when serializing to JSON. Currently what I am doing is declaring a public bool method for each readonly field in the class. This can get quite repetitive. JSON.Net has this feature that when you serialize it will check this public bool method and in there it will decide what to do. I have them all return false since I don't want them to be serialized. Referencing the ContractResolver I believe you can check if a property is readonly when serializing.

public bool ShouldSerializeLastModifiedDate()
        {
            return false;
        }

**Comment by wadewegner** [comment]
Any chance you can capture and example of the REQUEST/RESPONSE in Fiddler when this is happening? Or just share some code where it happens?

**Comment by LiquidSean** [comment]
User-Agent: Fiddler
Authorization: Bearer 
Host: na22.salesforce.com
Content-Length: 1986
Content-Type: application/json




HTTP/1.1 400 Bad Request
Date: Mon, 25 Jan 2016 17:41:42 GMT
Set-Cookie: BrowserId=BnBgEXjbQ5eVheEqpgtWzw;Path=/;Domain=.salesforce.com;Expires=Fri, 25-Mar-2016 17:41:42 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Sforce-Limit-Info: api-usage=928/15000
Content-Type: application/json;charset=UTF-8
Content-Length: 604

[{"message":"Unable to create/update fields: LastModifiedDate, JigsawCompanyId, LastReferencedDate, BillingAddress, CreatedById, PhotoUrl, IsDeleted, LastViewedDate, SystemModstamp, ShippingAddress, CreatedDate, LastModifiedById. Please check the security settings of this field and verify that it is read/write for your profile or permission set.","errorCode":"INVALID_FIELD_FOR_INSERT_UPDATE","fields":["LastModifiedDate","JigsawCompanyId","LastReferencedDate","BillingAddress","CreatedById","PhotoUrl","IsDeleted","LastViewedDate","SystemModstamp","ShippingAddress","CreatedDate","LastModifiedById"]}]

**Comment by wadewegner** [comment]
Is this still an issue? Please re-open if so.
