### ISSUE TITLE
Return more than 2000 records

### ISSUE THREAD

**Issue by eduarte** [developerforce/Force.com-Toolkit-for-NET#173]
Hi, 

I am using your toolkit, but I need to do some data comparison and I need to extract more than 2000 records.

I don't know if is implemented but in your documentation it doesn't said anything about it.

Thanks

**Comment by mp3tobi** [comment]
I think the problem is on the salesforce side:
https://developer.salesforce.com/docs/atlas.en-us.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_apicalls.htm

> WSC clients can set the batch size by calling setQueryOptions() on the connection object. C# client applications can change this setting by specifying the batch size in the call QueryOptions portion of the SOAP header before invoking the query() call. The maximum batch size is 2,000 records. However this setting is only a suggestion. There is no guarantee that the requested batch size will be the actual batch size. This is done to maximize performance.

> The batch size will be no more than 200 if the SOQL statement selects two or more custom fields of type long text. This is to prevent large SOAP messages from being returned.

**Comment by conficient** [comment]
You should use the `QueryContinuationAsync` method to get more records if you need to get all. 

This is a code fragment in my library that does this:
```
            var init = await client.QueryAsync<T>(tmpquery);
            var finished = false;
            do
            {
                finished = init.Done;

                // add any records
                if (init.Records.Any())
                    result.AddRange(init.Records);

                // if more
                if (!finished)
                {
                    // get next batch
                    init = await client.QueryContinuationAsync<T>(init.NextRecordsUrl);
                }
            } while (!finished);
```

**Comment by wadewegner** [comment]
Is this still an issue? Please re-open if so.

**Comment by VitaminC1211** [comment]
Hello, I can help you

**Comment by mp3tobi** [comment]
Problem is long solved with the QueryAllAsync Merge. :)
