### ISSUE TITLE
Use JsonPropertyAttribute rather than DataMemberAttribute for getting property names in QueryById

### ISSUE THREAD

**Issue by Blundell89** [developerforce/Force.com-Toolkit-for-NET#174]
Hi @wadewegner,

We have a model with properties that are annotated with the `JsonProperty` attribute. When we call `CreateAsync` our object is created in Salesforce as expected.

When using the `QueryByIdAsync<T>` method, we supply the same model for the query, which causes an exception. It looks like the `QueryByIdAsync<T>` implementation gets names from properties marked with the `DataMember` attribute.

Would it be possible to use the `JsonProperty` attribute for getting property names? As a workaround we have added both the `DataMember` attribute and `JsonProperty` attribute but this isn't particularly nice!

I don't mind doing a PR for the change if it would help out.

Thanks

**Comment by wadewegner** [comment]
Is this still an issue? Please re-open if so.
