### ISSUE TITLE
Issue with managed org

### ISSUE THREAD

**Issue by dibsranjan** [developerforce/Force.com-Toolkit-for-NET#175]
How do we query against a namespace org/managed org? if we change the namespace then we need to change the code also??

**Comment by wadewegner** [comment]
Sorry for the belated reply. Unfortunately, I don't understand what you're asking. Can you clarify and, if possible, give an example of what you're trying to do?

Given how long this has been open I'm going to close. But please feel free to re-open.

**Comment by cemerson** [comment]
I think I have same question. As discussed in [this thread](https://developer.salesforce.com/forums/?id=906F0000000DApiIAG) - if your SFDC has a custom namespace does this framework automatically inject that into the appropriate URLs or is there a CONSTANT we need to manually update before building?  

Example without a custom (managed package) namespace:
`https://na6.salesforce.com/services/apexrest/Test/TestRest`

Example WITH a custom (managed package) namespace:
`https://na6.salesforce.com/services/apexrest/mypackage/Test/TestRest`

**Comment by cemerson** [comment]
FYI I think I answered my own question ([here](https://developer.salesforce.com/forums/?id=906F0000000DApiIAG)) ... so I'm good.
