### ISSUE TITLE
Ability to ignore non-salesforce properties of bound object?

### ISSUE THREAD

**Issue by conficient** [developerforce/Force.com-Toolkit-for-NET#179]
I need to add some properties to my Account class that do not exist in the Salesforce model. When I try to execute `QueryByIdAsync<Account>(...)` I get the error `No such column 'xxxx' on entity 'Account'`.

I looked at the code for this method and it does not seem to provide a way to exclude an attribute: would it be possible to amend to support the [IgnoreDataMemberAttribute](https://msdn.microsoft.com/en-us/library/system.runtime.serialization.ignoredatamemberattribute%28v=vs.110%29.aspx) ?

**Comment by wadewegner** [comment]
Resolved and included in #204.

**Comment by conficient** [comment]
Many thanks - and thanks also for doing the .NET Standard version
