### ISSUE TITLE
TLS 1.0 Encryption Disabling by SalesForce

### ISSUE THREAD

**Issue by meenanarendra** [developerforce/Force.com-Toolkit-for-NET#181]
Hi Wade,

Good day and need your help here.

SFDC will be disabling support to TLS 1.0 Encryption my mid of this year in sandbox and early next year in production. Details in below link:

http://www.summa-tech.com/blog/salesforce-is-phasing-out-tls-1.0-support-take-action-now

We are using DeveloperForce.Force library to connect to sales force. Can you please let us know, if this TLS upgrade will have impact for our users?

Thank You
Narendra

**Comment by wadewegner** [comment]
Good question.

Today it's definitely using TLS 1.0 -- I just captured this with Wireshark:

![image](https://cloud.githubusercontent.com/assets/746259/13160604/3b851010-d64d-11e5-9542-64200fbab84d.png)

Typically you'd use `ServicePointManager` to manage the TLS version. However, this SDK uses portable class libraries, and it doesn't look like the `HttpClient` PCL supports `ServicePointManager`. Consequently, I'm not sure how this is managed.

I'll have to dig into this -- I'll get back to you.

**Comment by wadewegner** [comment]
This thread on Twitter seems to indicate it will just work: https://twitter.com/terrajobst/status/700513325528928257

**Comment by TommyRush** [comment]
I just started getting this error this morning: "TLS 1.0 has been disabled in this organization. Please use TLS 1.1 or higher when connecting to Salesforce using https" with the latest nuget DeveloperForce.Force (1.2.3).

**Comment by wadewegner** [comment]
Yes. Looks like we need to change out compression library. I will try to update this ASAP.

**Comment by mp3tobi** [comment]
Well, I think it's not only on the framework. With a quick hack in the registry you could use TLS 1.2 even in the .NET 4.5.x Versions.
https://help.salesforce.com/apex/HTViewSolution?id=000221207&language=en

I tried it and activated the new TLS 1.2 functionality and it works great within .NET 4.5.x

**Comment by wadewegner** [comment]
FYI: I was able to get a Salesforce org with TLS 1.0 turned off and sadly this is indeed a problem:

```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
System.Net.WebException : The request was aborted: Could not create SSL/TLS secure channel.
```

I don't know the right solution right now. The easiest approach I can think of is remove support Silverlight and Mono and go strictly with .NET 4.5+. I'm open to ideas.

**Comment by mp3tobi** [comment]
Do the community really need Silverlight Support?
I only use your package as a class in a console only project. It will run on a windows 7 computer. And therefore the registry hack works great. :)

Mono I think will nobody use.

**Comment by kleesman** [comment]
We use this library to offer Salesforce API integrations between our system and Salesforce and ran into a client today where this was an issue. It was hard to diagnose the root cause because salesforce was returning an HTML error page, which caused the JSON decoding to throw an exception. 

The message Salesforce returned was:
<h1>Stronger security is required</h1><div class="simple"><p>To access this website, update your web browser or upgrade your operating system to support TLS 1.1 or TLS 1.2.</p><p>For more information, see <a href="https://help.salesforce.com/HTViewSolution?id=000221207&amp;language=en_US" target="_blank">Salesforce disabling TLS 1.0</a>.

I don't really have any suggestions as to how to overcome this issue as my only thought was the ServicePointManager, which is not available in this project, but wanted to let you know that there are production organizations with SSL 1.0 disabled already.

**Comment by wadewegner** [comment]
Yes, I'm sorry @kleesman. Still working on a solution.

In emailing with Miguel it sounds as if Alpha Preview 1: Cycle 7 Updated 1 (wow, what a name!) adds TLS 1.2 support. https://releases.xamarin.com/alpha-preview-1-cycle-7/

I haven't dug into it beyond this but it's encouraging.

**Comment by mchorlton** [comment]
We have this issue too, is there any temporary workaround that doesn't involve editing registry keys?

**Comment by wadewegner** [comment]
I've confirmed that you can resolve this by explicitly setting the `SecurityProtocol` to `SecurityProtocolType.Tls12`.

```
// Use TLS 1.2 (instead of defaulting to 1.0)
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
```

I think it's time to remove support for Silverlight (given there's no access to `SecurityProtocol`. I'll track this separately.

**Comment by wadewegner** [comment]
See this update for example: https://github.com/developerforce/Force.com-Toolkit-for-NET/commit/9af33985c6870c1598a70169dbbc8026807c0fac

**Comment by Hikerakashiya** [comment]
@wadewegner, I am confused. Do applications that use the Force.com Toolkit for .NET have to have 
`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;` 
manually added or does the Toolkit take care of this so this is not something that has to be managed by the client? Considering this is a dependency between the toolkit and Salesforce shouldn't consumers of this toolkit not have to worry about this manual step?

**Comment by wadewegner** [comment]
Yes, you need to manually add. The SDK is (largely) platform agnostic whereas the way with which you specify TLS version is dependent on your platform.

**Comment by Hikerakashiya** [comment]
Thank you for confirming @wadewegner!
