### ISSUE TITLE
Silverlight 5

### ISSUE THREAD

**Issue by Bidou44** [developerforce/Force.com-Toolkit-for-NET#182]
I saw that this project is not compatible with Silverlight.

What should I do to make it compatible? Would it work if I change the code? I'm not sure, because the cross-domain policy problem will probably stay. Could you confirm?

Thanks.

Edit: I modified the code, now it runs with Silverlight. But I always get the "standard" Permission Exception. I really don't understand why Salesforce do not want to put the policy file on the server...

**Comment by wadewegner** [comment]
Glad you got it running with Silverlight.

If there's anything else you want to track let's open a new issue.
