### ISSUE TITLE
 The missing file is ..\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets.	Sensor Telemetry	

### ISSUE THREAD

**Issue by daruvurisai** [developerforce/Force.com-Toolkit-for-NET#184]
I am doing an application when i am trying to add the bcl library into packages using nuget package manager console i am getting this error when debugging the code.

**Comment by wadewegner** [comment]
I'm very sorry but I don't know how to help/support. What kind of project are you creating? What platform are you targeting? Lots of additional information needed. Going to close pending additional updates from you.
