### ISSUE TITLE
Merge the Bulk API into Master, please!

### ISSUE THREAD

**Issue by mp3tobi** [developerforce/Force.com-Toolkit-for-NET#185]
Hello.

Maybe it's a bit more complicated than I think. But what is the reason the most useful pull request in 2015 is not merged into master?
https://github.com/developerforce/Force.com-Toolkit-for-NET/pull/136

Please, please merge it. I need it and it would be very useful to use the bulk API via the nuget package. :)

Thanks
mp3tobi

**Comment by wadewegner** [comment]
You're welcome to merge this into your own fork. I'm honestly not certain that this pull request is the right solution and, yes, it's a bit of work to evaluate. We'll try to prioritize it.
