### ISSUE TITLE
need ability to set Request Headers

### ISSUE THREAD

**Issue by nagstaku** [developerforce/Force.com-Toolkit-for-NET#186]
When updating a lead, it automatically fires off lead assignment rules unless you set a request header.

https://developer.salesforce.com/docs/atlas.en-us.200.0.api_rest.meta/api_rest/headers_autoassign.htm

Sforce-Auto-Assign: FALSE

I verified in postman that I can add the headers to get the desired behavior but it doesn't appear we have any way of adding headers to the forceclient. Preferably I'd be able to set them when I use the method UpdateAsync as an optional parameter like such:

`public Task<SuccessResponse> UpdateAsync(string objectName, string recordId, object record, object headers = null);`

EDIT: I see there is a pull request from 19 November 2015 for this very feature

https://github.com/developerforce/Force.com-Toolkit-for-NET/pull/157

**Comment by wadewegner** [comment]
I haven't tested this, but couldn't you create your own `HttpClient` as follows and pass it in?

```
var httpClientTemp = new HttpClient();
httpClientTemp.DefaultRequestHeaders.TryAddWithoutValidation("Sforce-Auto-Assign", "FALSE");
```

You wouldn't want to use this `httpClient` for all your requests but as a one off this would work, right?

I'll review the linked pull request.

**Comment by wadewegner** [comment]
If this is still an issue (see latest updates to code) please re-open with more specifics.
