### ISSUE TITLE
DeveloperForce.Force 1.2.3 is not compatible with UAP,Version=v10.0.

### ISSUE THREAD

**Issue by watzon** [developerforce/Force.com-Toolkit-for-NET#187]
Are there any plans to make this compatible with UAP 10?

**Comment by wadewegner** [comment]
What is UAP?

**Comment by iDev0urer** [comment]
@wadewegner It's the windows Universal App Platform

**Comment by wadewegner** [comment]
If this is still an issue (see latest updates to code) please re-open with more specifics.
