### ISSUE TITLE
Example for ExecuteRestApiAsync ?

### ISSUE THREAD

**Issue by mp3tobi** [developerforce/Force.com-Toolkit-for-NET#190]
Hello.

I just wanted to fetch my remaining API Calls for the 24 hour window. Is there a method for that.
I already tried it via ExecuteRestApiAsync("limit"); But there was no API found. :(
Has anyone an idea how to get the remaining API Calls or an example on how to use the ExecuteRestApiAsync method?

Thanks, mp3tobi

**Comment by wadewegner** [comment]
Here's one possible way we could make this work. What do you think?

https://github.com/developerforce/Force.com-Toolkit-for-NET/commit/c0661a2c132fc025613207652ec53e05be5174a2#diff-cd4a405be9790fb4bdd0290ab5f0842eR56

@dcarroll, interested in your thoughts too.

Things I don't like:

1. It appears that `Sforce-Limit-Info` doesn't come back consistently, so I had to write it in a method to check to see if the header exists.

2. It's attached to the `ForceClient` which means that even if you haven't made an API call you could check and find the value empty/null.

**Comment by mp3tobi** [comment]
Well that could the way I like. :)
Just reading ForceClient.ApiUsage and get the remaining calls or the calls I've made in the last 24 hours.

**Comment by wadewegner** [comment]
I haven't merged it in. I'm not that thrilled with the implementation. And I still haven't heard back from @dcarroll to get his take on it. ;-)

**Comment by indyHarcourt** [comment]
Any further take on this?  I'd love to see a working example of the ExecuteRestApiAsync.
Thanks.

**Comment by ddrinka** [comment]
Could you create API overloads with an `out ApiLimit`, which is set to null if not provided by the response, but is filled in if it's available in the headers?  There's not so many methods exposed so it might be a reasonable surface area to adjust.  It'd be great to have the utilized _and_ the available API counts provided by the header.

**Comment by wadewegner** [comment]
If this is still an issue (see latest updates to code) please re-open with more specifics.
