### ISSUE TITLE
Unable to login to a sandbox

### ISSUE THREAD

**Issue by abhidotnet** [developerforce/Force.com-Toolkit-for-NET#191]
How do I target a sandbox environment for testing? Is there some parameter that I need to pass to target a sandbox?

**Comment by mp3tobi** [comment]
Well yes there is a parameter called: "IsSandboxUser" if you are using the configurationmanager Variables from the simple Console Example:

`private static readonly string IsSandboxUser = ConfigurationManager.AppSettings["IsSandboxUser"];`

[https://github.com/developerforce/Force.com-Toolkit-for-NET/blob/master/samples/SimpleConsole/Program.cs](url)
