### ISSUE TITLE
Convert Lead to Contacts

### ISSUE THREAD

**Issue by jezguitarist30** [developerforce/Force.com-Toolkit-for-NET#193]
Is is possible to convert leads into contact using the API?

**Comment by wadewegner** [comment]
I'm not sure if this is available in the REST API. Looks like you can do it with the SOAP API, though: https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_calls_convertlead.htm

**Comment by wadewegner** [comment]
Confirmed this is not part of the REST API. However, you could consider building an Apex class to do this with minimal effort.
