### ISSUE TITLE
Error when inheriting object maps from a dictionary 

### ISSUE THREAD

**Issue by dannyb2100** [developerforce/Force.com-Toolkit-for-NET#194]
Error when inheriting object maps from a dictionary 

```

    Public Class Contact
     Inherits Dictionary(Of String, String)
     Protected Const SObjectTypeName As String = "Contact"

    Dim _Name As String

        Public Property Name As String
            Get
                Return _Name
            End Get
            Set(value As String)
                _Name = value
            End Set
        End Property
    End Class

    Private Async Function getContacts() As Task

        Dim auth = New AuthenticationClient()

        Dim client As New ForceClient(sfInstance.Value, sfToken.Value, sfApiv.Value)
        Dim qry As String = "SELECT Name FROM Contact"
        Dim accts As New List(Of Contact)
        Dim res = Await client.QueryAsync(Of Contact)(qry)
        Dim sb As New StringBuilder

        For Each var In res.Records
            sb.Append(String.Format("{0}, {1} <br />", "", ""))
        Next
        sfTest.InnerHtml = sb.ToString()
    End Function
```

> Unexpected character encountered while parsing value: {. Path 'records[0].attributes', line 6, position 21.
> 
> Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 
> 
> Exception Details: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path 'records[0].attributes', line 6, position 21.

Any insights?

**Comment by wadewegner** [comment]
If this is still an issue (see latest updates to code) please re-open with more specifics.
