### ISSUE TITLE
query percent fields?

### ISSUE THREAD

**Issue by mp3tobi** [developerforce/Force.com-Toolkit-for-NET#195]
I have a query and want to use the "queryAsync" Method.
But if I include fields that are in Salesforce from the type "percent" in my query I got an error with Newtonsoft.Json.JsonSerializationException

`    public class Abweichende_Artikeldaten__c
    {
        public const String SObjectTypeName = "Abweichende_Artikeldaten__c"; //Objektname in Salesforce

```
    //Ab hier die Feldnamen.
    public string Id { get; set; }
    public string BpID__c { get; set; }
    public bool IsDeleted { get; set; } //Gelöscht in Salesforce
    public string Account__c { get; set; } //benötigt die Salesforce Account ID
    public string Produkt__c { get; set; } //benötigt die Salesforce Product2 ID
    public double abweichenderPreis__c { get; set; }
    public string Kundenartikelnummer__c { get; set; }
    public bool Kein_abweichender_Rabatt_g_ltig__c { get; set; } //Wenn das angehakt ist, ist kein anderer Rabatt erlaubt!
    public bool Rabbatf_hig__c { get; set; } //Nur wenn das True ist, darf unten die Staffel benutzt werden.
    public double Preis_gilt_f_r_Menge__c { get; set; }

    public double Menge_1__c { get; set; }
    public double Menge_2__c { get; set; }
    public double Menge_3__c { get; set; }
    public double Menge_4__c { get; set; }
    public double Menge_5__c { get; set; }
    public double Menge_6__c { get; set; }

    public double Preis_1__c { get; set; }
    public double Preis_2__c { get; set; }
    public double Preis_3__c { get; set; }
    public double Preis_4__c { get; set; }
    public double Preis_5__c { get; set; }
    public double Preis_6__c { get; set; }

    public double Rabatt_1__c { get; set; }
    public double Rabatt_2__c { get; set; }
    public double Rabatt_3__c { get; set; }
    public double Rabatt_4__c { get; set; }
    public double Rabatt_5__c { get; set; }
    public double Rabatt_6__c { get; set; }

}`
```

Rabatt_1__c till Rabatt_6__c are in Salesforce in the type of percent.
If I'm writing data via the create method or update method there is no problem.
But with the query to write the result in the list there is the error:

`            var client = new ForceClient(InstanceUrl, AccessToken, ApiVersion);

```
        var abweichendeArtikeldaten = new List<Abweichende_Artikeldaten__c>();
        var results = await client.QueryAsync<Abweichende_Artikeldaten__c>(qry);
        var totalSize = results.TotalSize;`
```

Hope anybody could help. Or do I really need to make the call via Dynamics?

**Comment by mp3tobi** [comment]
Well I got my error.
I query some datasets with some fields which contains nothing.
So NULL to Double is not allowed in c# and that throws me an error.

So maybe I change the standard information for the double, percent fields to 0 if there are no user value entered. 

Or have you another good implementation how I could catch the null value, change it to 0 and enter the 0 value to my double member field?

**Comment by wadewegner** [comment]
Can't you do something like:
```
public double? Rabatt_6__c {get;set; }
```

**Comment by mp3tobi** [comment]
Thanks for the hint about nullable operator.
