### ISSUE TITLE
UpdateAsync makes null property erase target property?

### ISSUE THREAD

**Issue by nagstaku** [developerforce/Force.com-Toolkit-for-NET#197]
Per your code example for update:
***
You can update an object:

var account = new Account() { Name = "New Name", Description = "New Description" };
var id = await client.CreateAsync("Account", account);

account.Name = "New Name 2";

var success = await client.UpdateAsync("Account", id, account);
***

In my attempts, if account.Description = null when doing an update, and the value on Salesforce is set, then it will delete it.

Is there a way to make it only update values that are set?

**Comment by wadewegner** [comment]
This shouldn't happen and I thought we had it set to ignore nulls on updates. I'll take a look.

**Comment by nagstaku** [comment]
Oh that would be great if this was fixed. It leaves the question though of how to delete a field on purpose. My temporary work around was to serialize an object to JSON and then back to a dynamic object.

It looks like the SOAP API has an additional object noted as such:

> 
> Resetting Values to null
> To reset a field value to null, you add the field name to the fieldsToNull array in the sObject. You cannot set required fields (nullable is false) to null.

**Comment by chuckwhite279** [comment]
I am running into this issue too.  When I do an UpdateAsync trying to update one field, I get a success back but any field not sent with the update is deleted.

forceClient.UpdateAsync("MyObjectType__c", idStringFromAnotherMethod, new {fieldToUpdate = true}) wipes out any other field.  I'm working on the json workaround nagstaku noted above but I'm hitting exceptions at the moment.

**Comment by wadewegner** [comment]
Working with @chuckwhite279 I finally can reproduce the issue and think I have a fix. Testing and will update soon.

**Comment by wadewegner** [comment]
Here's the [proposed fix](https://github.com/developerforce/Force.com-Toolkit-for-NET/commit/b50bc4b55e84db180a868c152fb657f2481a1cc5?diff=unified#diff-e1a2c705e38e9ca0c8fee5b3414878fe). All tests pass.

**Comment by wadewegner** [comment]
@chuckwhite279 just confirmed this fixed solved his issue. I'll package and publish v1.3.1 with this fix shortly.

**Comment by wadewegner** [comment]
Published: https://www.nuget.org/packages/DeveloperForce.Force/1.3.1

Thanks @chuckwhite279 and @nagstaku for your help!

**Comment by rumatavz** [comment]
How can I set some field to null after this changes?

**Comment by talbotmcinnis** [comment]
Indeed.  How do we now clear a nullable datetime field!?

**Comment by ngallegos** [comment]
@wadewegner, do you have an answer on how to set a field to null after this change?  I've tried setting the fieldsToNull property to an array of the field names I want to set as null as described [here](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_calls_concepts_core_data_objects.htm#i1421117), but SalesForce just returns an error saying that the 'fieldsToNull' column doesn't exist.  Setting the field to null on the object I pass does not set it to null either.

**Comment by gconry18** [comment]
@ngallegos I spent the day looking at this for our companies integration. fieldsToNull seems to be for the SOAP API and not the REST API that this toolkit uses.
For the rest API you can include the null in the json, however, the toolkit is designed to not add any null value fields to the json so that partial updates are possible. You can just use a blank string as the value which should clear out the field.

**Comment by gconry18** [comment]
@wadewegner @rumatavz @talbotmcinnis @ngallegos 
I have created pull request #268 which allows you to specify whether or not null columns should serialize and be sent to the API.

**Comment by ngallegos** [comment]
@gconry18, looks great! Thanks for looking into this.

**Comment by naicud** [comment]
Hi,
Here is my solution:

using Newtonsoft.Json.Linq;
using Salesforce.Common;
using Salesforce.Common.Models.Json;
using Salesforce.Force;
using System.Threading.Tasks;

// object class to update on salesforce
public class ObjectToUpdate
{
        public string Name {get;set;}
        
        // the salesForce dll build the api's call on json so you must to enable "NullValueHandling" for specific property
        [JsonProperty(NullValueHandling = NullValueHandling.Include)]
        public string Date {get;set;}
}
public class businessLogic
{
   public void customMethodUpdateSales()
   {

    using (ForceClient ForceClient= GetSfClient())
     {
         var objToUpdate = new ObjectToUpdate{ Name ="Pippo", Date = null};
        var id = "Your salesforce object toupdate id";
        var entityToUpdate "Your salesforce object name to update";
        await ForceClient.UpdateAsync(entityToUpdate, id, objToUpdate );
      }
     }
}
