### ISSUE TITLE
List of objects which can be managed

### ISSUE THREAD

**Issue by toprysk** [developerforce/Force.com-Toolkit-for-NET#199]
I start to use Force.com-Toolkit-for-NET in my project. At the moment I know how to work with Account, Contact and Lead, but it is importantly for me to work with Report (create, get data, update and delete).
I can get some data of report (id, name, description, folder name), but can't create, update or delete.
Can You, please, provide me with information what actions we can use for SalesForce Reports!

**Comment by wadewegner** [comment]
Please start with the Salesforce documentation.
