### ISSUE TITLE
Authentication Issue

### ISSUE THREAD

**Issue by sabindangol** [developerforce/Force.com-Toolkit-for-NET#200]
Hi,

I get this error from time to time when authenticating with Salesforce: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

I get this error for this part of code:
await auth.UsernamePasswordAsync(myProperty.ConsumerKey, myProperty.ConsumerSecret, myProperty.Username, myProperty.Password, url);

I am trying to sync data from my app to Salesforce. It tries to sync every 15 minutes. It fails only sometimes.

Please help.

**Comment by mchorlton** [comment]
I am also getting the same issue. Production system with no changes was working fine a few days ago, now every call to ```await authenticationClient.UsernamePasswordAsync(_clientId, _clientSecret, _username, _password + _token);``` results in either a generic ```retry your request``` or ```Unexpected character encountered while parsing value: <. Path '', line 0, position 0.```

Please advise.

**Comment by benerdin** [comment]
I believe this issue was already answered a few times. Check out the discussions in these closed issues: https://github.com/developerforce/Force.com-Toolkit-for-NET/issues/181, https://github.com/developerforce/Force.com-Toolkit-for-NET/issues/203

**Comment by mchorlton** [comment]
Thanks for the swift response. That has solved the problem.
