### ISSUE TITLE
AuthenticationClient.TokenRefreshAsync Missing RefreshToken

### ISSUE THREAD

**Issue by Hikerakashiya** [developerforce/Force.com-Toolkit-for-NET#201]
After calling AuthenticationClient.TokenRefreshAsync, the RefreshToken is null in the AuthenticationClient object. How are we suppose to do a token refresh in the future after the first refresh token is used and another one is never populated? This appears to be a bug.

**Comment by Hikerakashiya** [comment]
@wadewegner can you please look into this?

**Comment by wadewegner** [comment]
Are you sure you have `Perform requests on your behalf at any time (refresh_token, offline_access)` set in your Connected App?

![image](https://cloud.githubusercontent.com/assets/746259/17192014/926b52cc-5401-11e6-9016-25e566849281.png)

**Comment by wadewegner** [comment]
I found the bug. Working on a fix. So sorry.

**Comment by wadewegner** [comment]
I see what's happening here. You're expecting a new `RefreshToken`? You won't get one. 

Here's the response you get from `https://login.salesforce.com/services/oauth2/token?grant_type=refresh_token...`:

```
{
   "access_token":"<snip>",
   "signature":"<snip>",
   "scope":"refresh_token visualforce wave_api custom_permissions web openid chatter_api id api full",
   "instance_url":"https://na10.salesforce.com",
   "id":"https://login.salesforce.com/id/<snip>",
   "token_type":"Bearer",
   "issued_at":"1469654465944"
}
```

You don't get another refresh token. You need to use the original.

The reason the value is null is because there's nothing to grab. What behavior would you prefer?

**Comment by wadewegner** [comment]
Would you rather I add the refresh token you passed into the method back into the `RefreshToken`?

**Comment by wadewegner** [comment]
See if this helps you: https://github.com/developerforce/Force.com-Toolkit-for-NET/commit/9b9de8c0f6ded10133f63fee06034a7781100176

**Comment by wadewegner** [comment]
I decided this was a valuable addition and went ahead and generated a new package. Grab v1.3.2.

**Comment by Hikerakashiya** [comment]
I assumed that after you use the Refresh Token, it expired like the Access Token. So I was expecting a new Refresh Token returned in the AuthenticationClient object after calling AuthenticationClient.TokenRefreshAsync. I did not realize the Refresh Token stayed valid and all you needed to do was preserve the original Refresh Token. Thanks for making this change.

**Comment by arnigunnar** [comment]
Hi. Just wanted to drop a comment, although this is a closed issue. I was expecting the same behaviour as the OP and in the response the RefreshToken was empty, and when I updated the nuget package, all was good. Well done!
