### ISSUE TITLE
Cannot add current nuget package to ASP.NET CORE 1.0

### ISSUE THREAD

**Issue by masaab** [developerforce/Force.com-Toolkit-for-NET#202]
I am trying to add the package to my asp.net core 1.0 project. It is throwing an error 
**Package DeveloperForce.Force 1.3.0 is not compatible with netcoreapp1.0**.

Can we create a package that supports .net core.

**Comment by wadewegner** [comment]
Duplicate: 
https://github.com/developerforce/Force.com-Toolkit-for-NET/issues/196
