### ISSUE TITLE
Ability to customize Select List when using QueryByIdAsync<T>()

### ISSUE THREAD

**Issue by avesse** [developerforce/Force.com-Toolkit-for-NET#209]
This is really just a consolidation of issues #171 #174 #179. 

We need the ability to customize what goes into the SELECT list for the SOQL query for ForceClient.QueryByIdAsync<T>().

**Comment by avesse** [comment]
Created pull request which should resolve this - https://github.com/developerforce/Force.com-Toolkit-for-NET/pull/210

**Comment by wadewegner** [comment]
Merged https://github.com/developerforce/Force.com-Toolkit-for-NET/pull/210. Thanks.
