### ISSUE TITLE
Using this to deploy a zip package

### ISSUE THREAD

**Issue by watzon** [developerforce/Force.com-Toolkit-for-NET#213]
I'm wondering if a method exists for this and I just missed it. In JSForce it's the Metadata.deploy() method, but what I'm looking for is a way to deploy a zipped package with a package.xml file in it.

Ex: a zipped version of the following

``` shell
package
├── classes
│   ├── IndexController.cls
│   ├── IndexController.cls-meta.xml
├── package.xml
├── pages
│   ├── Index.page
│   ├── Index.page-meta.xml
└── staticresources
    └── StaticAssets.resource
```

**Comment by wadewegner** [comment]
If this is still an issue (see latest updates to code) please re-open with more specifics.
