### ISSUE TITLE
WiKi - Sample code wrong function name?

### ISSUE THREAD

**Issue by rjiang9** [developerforce/Force.com-Toolkit-for-NET#214]
In 'Getting Started' section: 

**Username-Password Authentication Flow**

`var auth = new AuthenticationClient();
await auth.UsernamePassword("YOURCONSUMERKEY", "YOURCONSUMERSECRET", "YOURUSERNAME", "YOURPASSWORD");`

`UsernamePassword` should be `UsernamePasswordAsync`. Shouldn't it?

**Comment by wadewegner** [comment]
If this is still an issue (see latest updates to code) please re-open with more specifics.
