### ISSUE TITLE
Execute multiple requests in a single API call - support for Composite Resources 

### ISSUE THREAD

**Issue by kevmcivor** [developerforce/Force.com-Toolkit-for-NET#215]
It is possible to Use the Batch resource to execute multiple requests in a single API call

https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_composite_batch.htm#topic-title

Can support for this be introduced to the toolkit?

**Comment by seankearon** [comment]
+1 - that would be really useful.

**Comment by seankearon** [comment]
Actually, I think the link to the docs is this one, or have I missed something?

https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_composite_sobject_tree_flat.htm

**Comment by wadewegner** [comment]
If this is still an issue (see latest updates to code) please re-open with more specifics.
