### ISSUE TITLE
Is There Any API For Create Support Issues and Get Updates ? 

### ISSUE THREAD

**Issue by bhallaheemanshu** [developerforce/Force.com-Toolkit-for-NET#218]
does salesforce provide any api for creating support issues directly from api and get updates on that particular support issues ?

I could't find i thought i may be missing it

**Comment by wadewegner** [comment]
I don't believe so. This SDK certainly doesn't.

**Comment by bhallaheemanshu** [comment]
@wadewegner Thanks for the info . I appreciate your quick reply

**Comment by wadewegner** [comment]
If you have general questions I'd suggest you take them to the [Salesforce StackExchange](http://salesforce.stackexchange.com/). This repository is specific to the Salesforce .NET SDK.

**Comment by bhallaheemanshu** [comment]
@wadewegner  ok thanks I will be heading towards that LINK
