### ISSUE TITLE
How To Get SecurityToken ?

### ISSUE THREAD

**Issue by bhallaheemanshu** [developerforce/Force.com-Toolkit-for-NET#219]
**I have seen Password is concatinated with SecurityToken But how can i get SecurityToken**

private static readonly string SecurityToken = ConfigurationManager.AppSettings["SecurityToken"];
      
   private static readonly string Password = ConfigurationManager.AppSettings["Password"] + SecurityToken;

**Comment by wadewegner** [comment]
Here you go: http://lmgtfy.com/?q=salesforce+security+token
