### ISSUE TITLE
sample code in readme is incorrect

### ISSUE THREAD

**Issue by cboseak** [developerforce/Force.com-Toolkit-for-NET#221]
In the readme, one of the sections of code samples calls a method with an incorrect signature.

In the section of _"var client = new ForceClient(_consumerKey, _consumerSecret, _username, _password);"_ ForceClient does not have a constructor with a signature like this. The only option is _"var client = new ForceClient(instanceUrl, accessToken, apiVersion);"_

**Comment by wadewegner** [comment]
If this is still an issue (see latest updates to code) please re-open with more specifics.
