### ISSUE TITLE
support sessionId (Authorization: OAuth)

### ISSUE THREAD

**Issue by brethren70** [developerforce/Force.com-Toolkit-for-NET#226]
Can you support sessionId?
Login with Soap is convenient(only UserId and Password are needed)
So I want to login with soap and do other stuff with your toolkit.

Thanks in advance.

-=-=-=-=-=-=-=-=-=-=-=-=-=-=
_httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
----->
httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("OAuth", sessionId);

**Comment by wadewegner** [comment]
If this is still an issue (see latest updates to code) please re-open with more specifics.
