### ISSUE TITLE
Trouble logging into sandbox due to TLS 1.1 requirement

### ISSUE THREAD

**Issue by TJSoftware** [developerforce/Force.com-Toolkit-for-NET#227]
I am using your [SimpleConsole](https://github.com/developerforce/Force.com-Toolkit-for-NET/tree/master/samples/SimpleConsole) sample with the App.config modified to use my data.  The only modification to the code was to place a try catch around the `await auth.UserNamePasswordAsync(...`.

I was able to log onto our production without issue.  When I modify the URL to either `https://test.salesforce.com/services/oauth2/token` or `https://cs10.salesforce.com/services/oauth2/token`  I receive an exception when calling `await auth.UsernamePasswordAsync(ConsumerKey, ConsumerSecret, Username, Password, url);`.  `retry your request` for the first and `Unexpected character encountered while parsing value: <. Path '', line 0, position 0.` for the cs10 url.

I did some further digging.  By that I mean I took `UsernamePasswordAsync` created a private method and called that instead of the library version.  Debugging that I could see the error more clearly was a page returned with a message from SalesForce stating that there was an Internal Exception, that is where the parse error was happening.  The internal exception error was due to a change that requires TLS 1.1 and newer to be used.  This can be accomplished by adding one line of code before the HttpRequestMessage see below and the login for my sandbox started to work.

```
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 |     SecurityProtocolType.Tls;
var request = new HttpRequestMessage
{
   Method = HttpMethod.Post,
   RequestUri = new Uri(tokenRequestEndpointUrl),
   Content = content
};
```

**Comment by TJSoftware** [comment]
Nevermind, when I forked your repo I noticed you are using a PCL, I did not notice that before.  ServicePointManager is in System.Net.

**Comment by vyacheslav-lonschakov** [comment]
Thx, line below fixed error HTTP 400 Bad Request {"error":"unknown_error","error_description":"retry your request"} for me.

`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls11;`

**Comment by StingyJack** [comment]
I was getting this today and it was because the url I had been using (from the examples) no longer works. 

used this before recently..
> https://login.salesforce.com/services/oauth2/Token

only this works now
> https://login.salesforce.com/services/oauth2/token

the capitalized Token makes salesforce return a 404.

**Comment by wadewegner** [comment]
If this is still an issue (see latest updates to code) please re-open with more specifics.

**Comment by TJSoftware** [comment]
I don't recall all the details, but I know that I made my own branch of this. I then updated for the call to use TLS 1.1. I also updated everything to use async calls. I would need to rebuild everything I did as I do not work at the place I used this any more. Sorry for the hanging bug.

**Comment by wadewegner** [comment]
No worries. I actually don't think this is still an issue. If someone says it is, we'll look into it. Thanks!
