### ISSUE TITLE
Deserialize a dynamic object from queryAll<dynamic> to Object

### ISSUE THREAD

**Issue by joaopaulonobrega** [developerforce/Force.com-Toolkit-for-NET#229]
How to descerialize a dynamic object from queryAllAsync(query) to object ? , my query has a parent relations, e.g 

```
        public async Task<dynamic> AllAsync(string quoteId) 
        {
            var query = new StringBuilder();
            query.Append("SELECT Product2.Part_Number__c, Product2.Name, Quantity, UnitPrice, TotalPrice FROM QuoteLineItem ");
            query.Append(String.Format("WHERE QuoteId= '{0}' ", quoteId));          

            var context = await SalesforceService.GetUserNamePasswordForceClientAsync();
            var queryResult = await context.QueryAllAsync<dynamic>(query.ToString());

            return queryResult.Records;
        }
```

 it is possible? tnks

**Comment by itsvkee** [comment]
`
 List<Dictionary<string, string>> listDic = new List<Dictionary<string, string>>();
 var cont = var queryResult = await context.QueryAllAsync<dynamic>(query.ToString());
                    foreach (var c in cont.Result.Records)
                    {
                        Dictionary<string, string> newDict = ((IEnumerable<KeyValuePair<string,   JToken>>)c).ToDictionary(kvp => kvp.Key, kvp => kvp.Value.ToString());
                        listDic.Add(newDict);
                    }`


try like this.

**Comment by wadewegner** [comment]
If this is still an issue (see latest updates to code) please re-open with more specifics.
