### ISSUE TITLE
Time to deploy 1.3.3?

### ISSUE THREAD

**Issue by marknadig** [developerforce/Force.com-Toolkit-for-NET#235]
Last drop to nuget was July.  Thanks for considering.
Mark

**Comment by tomlyner** [comment]
This would be useful. Especially the change which made `IAuthenticationClient` public.

**Comment by marknadig** [comment]
@wadewegner what say you?

**Comment by wadewegner** [comment]
Let's do it. =)

Just need a few days and I'll get to this!

**Comment by wadewegner** [comment]
I'm sorry, friends! It's been way too long.

I just merged a pretty big update that supports the bulk API. So, before just pushing it out, figured I'd release a beta. Give it a go?

https://www.nuget.org/packages/DeveloperForce.Force/1.4.0-beta
https://www.nuget.org/packages/DeveloperForce.Chatter/1.4.0-beta

Thanks!
