### ISSUE TITLE
Custom Field Strongly-Typed Naming

### ISSUE THREAD

**Issue by brentpabst** [developerforce/Force.com-Toolkit-for-NET#243]
Hi,

We've got a boat load of custom fields in our org.  We are following most of the examples in terms of defining strongly-typed objects and then loading data into them from the SDK.  However, I would really like to follow clean and consistent naming practices in our strongly-typed object so instead of ```My_Custom_Field__c``` I could do something like this:

```
[SFName(Name = "My_Custom_Field__c")]
public string CustomField {get;set;}
```

Perhaps I've missed how this can be done already, if so updates to the docs would be appreciated!

**Comment by avesse** [comment]
You can use the [DataMember] attribute. 

I've also got a pull request #210 pending which will let you use [JsonProperty] or any custom resolver for field names.

**Comment by brentpabst** [comment]
@avesse Thanks, I wasn't able to get DataMember to work properly... values are null when run.

```
[DataMember(Name = "Renewal_Date__c")]
public string RenewalDate { get; set; }
```

**Comment by ddrinka** [comment]
@brentpabst Make sure your POCO is marked with [DataContract]

**Comment by avesse** [comment]
@brentpabst What method are you running? 

Just looked at the code again and it looks like `[DataMember]` is only used by the `QueryByIdAsync` method. The rest of the methods use Json.Net, so you should be able to use `[JsonProperty]` (although this will break `QueryByIdAsync`).

**Comment by brentpabst** [comment]
This works:

```
[JsonProperty(PropertyName = "Renewal_Date__c")]
public string RenewalDate { get; set; }
```

I think the reason I didn't think it was working when I tried it before is that we are logging the objects back out to stdout using ```_logger.Debug(JsonConvert.SerializeObject(record));``` and the JSON serialization works both ways so you won't see the strongly-typed name when logged, just the SF field name. That's a little crappy when troubleshooting but at least our POCOs will be cleaner.

If I have time I may send up a PR with some documentation or examples of overriding the property names.
