### ISSUE TITLE
InstanceURL = null sometimes but internet connection is ok.

### ISSUE THREAD

**Issue by mp3tobi** [developerforce/Force.com-Toolkit-for-NET#245]
Has anybody an idea, why I sometimes got an error with ending in `auth.InstanceUrl = null` ?
I just login to Salesforce every 15 Minuten around 15 times because I got 15 methods which login everyone individually since I got no idea how pass the session from one object instance to another.

But sometimes my computer got an internet connection but maybe failed to logon to Salesforce and ended up in getting `auth.InstanceUrl = null` 

Any idea?

My authmethod is here:

`        //Salesforce Auth Instanz Variablen:
        private string InstanceUrl { get; set; }
        private string AccessToken { get; set; }
        private string ApiVersion { get; set; }

        public async Task Login()
        {
            var auth = new AuthenticationClient();

            // Authenticate with Salesforce
            Console.WriteLine("Authenticating with Salesforce");
            var url = IsSandboxUser.Equals("true", StringComparison.CurrentCultureIgnoreCase)
                ? "https://test.salesforce.com/services/oauth2/token" //Neue Test-URL: https://h-team--entwicklun.cs89.my.salesforce.com/services/oauth2/token
                : "https://login.salesforce.com/services/oauth2/token"; //Neue URL: https://h-team.my.salesforce.com/services/oauth2/token

            await auth.UsernamePasswordAsync(ConsumerKey, ConsumerSecret, Username, Password, url);
            Console.WriteLine("Connected to Salesforce");

            if (auth.InstanceUrl != null && auth.AccessToken != null && auth.ApiVersion != null)
            {
                InstanceUrl = auth.InstanceUrl;
                AccessToken = auth.AccessToken;
                ApiVersion = auth.ApiVersion;
            }
            else //Wenn eine dieser Variablen NULL ist, macht es keinen Sinn weiterzumachen!
            {
                bool Erfolg = false;
                string body = "auth.instanceUrl = " + auth.InstanceUrl + "; auth.AccessToken = " + auth.AccessToken + "; auth.ApiVersion = " + auth.ApiVersion; 
                Erfolg = aiStandard.Mail.Mail_versenden("t.aichele@h-team.de", "Synchronisation - BP zu SF hat sich beendet...", body);
                BpNextConnection.BPKill();
                Environment.Exit(0);
            }
        }`

And my typical create method:

`        public async Task CreateRecord()
        {
            var client = new ForceClient(InstanceUrl, AccessToken, ApiVersion);

            // Create Record
            Console.WriteLine("Creating record.");
            var response = await client.CreateAsync(SFobjectName, SFobject);
            SFID = response.Id;
            if (SFID == null)
            {
                Console.WriteLine("Failed to create record.");
                return;
            }
            Console.WriteLine("Successfully created record. ID: " + SFID + " in " + SFobjectName);
        }`

Thanks for any idea!

I think my workaround in closing the program if instanceURL = null should help me a bit, but it's not the elegant method. ;)

**Comment by wadewegner** [comment]
If this is still an issue (see latest updates to code) please re-open with more specifics.

**Comment by leobel** [comment]
Hi, I'm using the latest nuget version of DeveloperForce.Force (2.0.7) and I'm facing the dame issue. Any idea?

**Comment by leobel** [comment]
Does it anything to do with multiple connections opens at a time?
