### ISSUE TITLE
Missing Salesforce.Force.dll

### ISSUE THREAD

**Issue by vonvillaruel** [developerforce/Force.com-Toolkit-for-NET#271]
I'm trying to run the SimpleBulkConsole project and already added the ForceToolkitForNET as the reference. When I running the build solution, this error below is showing. I'm not a .net developer your response will be helpful.
Metadata file 'C:\Users\von.c.v.villaruel\Desktop\DotNet\SimpleBulkConsole - Copy\ForceToolkitForNET\bin\Debug\Salesforce.Force.dll' could not be found

**Comment by AlmasMahfooz** [comment]
@vonvillaruel I am also trying to find this dll, how can I have it?

**Comment by vonvillaruel** [comment]
@AlmasMahfooz look for SFBulkAPIStarter package instead. I'm now using this to connect with Salesforce

**Comment by AlmasMahfooz** [comment]
@vonvillaruel  thank but still I am confused. Like you I am also not a .Net developer.
I am Microsoft Dynamics GP Developer.I am confused with this toolkit idea. When we install Dynamics GP VSTool kit (it has it's setup) it gives us an interface by using which we leverage Dynamics GP functionalities. See screen shots below. And References show respective dlls in project. 
![image](https://user-images.githubusercontent.com/14289694/38240942-5fa3fe7e-374a-11e8-84db-7ec8e037e5b4.png)

How exactly I can install this Force.com toolkit? and how to use them.
All I see sample projects and even those projects are missing dlls.
![image](https://user-images.githubusercontent.com/14289694/38241099-d365b366-374a-11e8-8520-e85634d92997.png)


I am not aware of NuGet as I already mentioned I am not .NET developer and never used it. So how exactly I can have these dlls, reference them on my project and establish a login to SF.
