### ISSUE TITLE
app stopped authenticate Salesforce

### ISSUE THREAD

**Issue by AharonShachar** [developerforce/Force.com-Toolkit-for-NET#274]
Yesterday I saw that the Dll failed authenticate SalesForce. The error I get is:

Message "authentication failure"
Error InvalidGrant Salesforce.Common.Models.Error

it use to run perfectly - any idea why Im getting this now?

No change has done with the user credentials.

**Comment by AharonShachar** [comment]
related to [https://github.com/developerforce/Force.com-Toolkit-for-NET/issues/262](url)

**Comment by afkhalid** [comment]
Try this completely 

http://www.calvinfroedge.com/salesforce-how-to-generate-api-credentials/

**Comment by lazoras** [comment]
I'm having this issue too. i can get the request to succeed in postman, but i cant get it to succeed using this library.

**Comment by wadewegner** [comment]
If this is still an issue (see latest updates to code) please re-open with more specifics.
