### ISSUE TITLE
DeveloperForce 1.3.2 Incompatible with .Net 4.6.1

### ISSUE THREAD

**Issue by DavidVeksler** [developerforce/Force.com-Toolkit-for-NET#275]
Reproduced using a new 4.6.1 project:
[stacktrace.txt](https://github.com/developerforce/Force.com-Toolkit-for-NET/files/1422398/stacktrace.txt)

This fails:
`ForceClient client = new ForceClient(auth.InstanceUrl, auth.AccessToken, auth.ApiVersion);`
Because of this error:
"Method not found: 'Void Salesforce.Force.ForceClient..ctor(System.String, System.String, System.String, System.Net.Http.HttpClient)'."
The System.Net.Http version in 4.6.1 is 4.0.0.0.  I've tried an assembly binding redirect, but the 
packages wants a specific version.

**Comment by DavidVeksler** [comment]
Update: confirmed that this is fixed in the 1.4 beta.  
Unfortunately, my team spent two days on this issue before discovering this.

**Comment by Paul-Schroeder** [comment]
Wow...wow...wow, thanks David.  We too burned a lot of time on this one.  Your comment validated what I suspected.  Almost one year later and v1.4 remains in beta, but at least it fixed the issue!

**Comment by wadewegner** [comment]
Apologies.

I've already ported everything to net core/standard and will push new packages soon.
