### ISSUE TITLE
using client.RunJobAndPollAsync

### ISSUE THREAD

**Issue by prices1964** [developerforce/Force.com-Toolkit-for-NET#277]
Hi

I have downloaded and used this wonderful library for months and its great. I want now to use the Bulk Upload methods but I do not see the RunJobAndPollAsync on my ForceClient object. I am using 1.3.2 

Any help appreciated 

Thanks

Steve

**Comment by alcidesfmelof** [comment]
I have the same issue. How to use the RunJobAndPollAsync?

**Comment by crtjr64** [comment]
I didn't find it either... had to download the 1.4-beta version to get it... they never said a word and I'm currently dealing with issues of data size... thus far, 3k records is out the question, down to 100.

**Comment by wadewegner** [comment]
Sorry, bulk will be in the next public release.
