### ISSUE TITLE
ForceClient.QueryByIdAsync<T> does not support the exclusion of relationship fields

### ISSUE THREAD

**Issue by mrrobdlon** [developerforce/Force.com-Toolkit-for-NET#278]
We have models that include fields such as MyFavouriteUser__r

We need these fields on our models when performing write operations.

When ForceClient.QueryByIdAsync<T> is used with a T that includes relationship fields, it raises an exception.

Is there a way to prevent this, other than removing the properties from the model class?

Looking at the code for the method it would seem feasible to implement support for a new attribute such as [IgnoreForSelect]?

**Comment by wadewegner** [comment]
If this is still an issue (see latest updates to code) please re-open with more specifics.

**Comment by mrrobdlon** [comment]
Thanks @wadewegner, will do
