### ISSUE TITLE
Is this repo abandoned?

### ISSUE THREAD

**Issue by avesse** [developerforce/Force.com-Toolkit-for-NET#279]
Last commit is nearly a year ago, pull requests are not getting approved or rejected, and the nuget package, as it stands, does not support bulk operations or the latest TLS requirements from Salesforce.

Does Salesforce intend to support a .NET client going forward?

**Comment by marknadig** [comment]
Perhaps reach out to Wade Wegner?
https://developer.salesforce.com/blogs/developer-relations/2014/01/announcing-the-salesforce-toolkits-for-net.html

**Comment by tj2480** [comment]
@wadewegner is this going to be supported going forward?

**Comment by rdev5** [comment]
@avesse See also https://github.com/developerforce/Force.com-Toolkit-for-NET/pull/248 for an implementation of a new `IBulkForceClient` interface. We're still using it in the interim.

**Comment by wadewegner** [comment]
I'll start investing the time to see what I can do to make this compliant with both .NET (I haven't tracked for years) and the latest Salesforce requirements.

**Comment by wadewegner** [comment]
All the code has been ported to net core/standard. I will continue and push updated packages soon.
