### ISSUE TITLE
Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by psmak4** [developerforce/Force.com-Toolkit-for-NET#281]
I get this error doing the WebServer OAuth flow in my callback.
`var consumerKey = ConfigurationManager.AppSettings["SalesForceConsumerKey"].ToString();
var consumerSecret = ConfigurationManager.AppSettings["SalesForceConsumerSecret"].ToString();
var callbackUrl = ConfigurationManager.AppSettings["SalesForceAuthorizationCallbackUrl"].ToString();
var tokenRequestEndpointUrl = ConfigurationManager.AppSettings["SalesForceTokenRequestEndpointUrl"].ToString();
var auth = new AuthenticationClient();
await auth.WebServerAsync(consumerKey, consumerSecret, callbackUrl, code, tokenRequestEndpointUrl);`
The code errors on the "auth.WebServerAsync" call.

**Comment by psmak4** [comment]
After digging into this a bit more, I'm finding the response being sent back to my server is a HTML page that says "Stronger security is required" and "To access this website, update your web browser or upgrade your operating system to support TLS 1.1 or TLS 1.2.". The problem is I'm using Chrome 63 with TLS 1.1 and 1.2 enabled. What am I missing here?

**Comment by avesse** [comment]
This might be useful: https://github.com/developerforce/Force.com-Toolkit-for-NET/issues/262

**Comment by psmak4** [comment]
Yes! That worked. Thank you so much.
