### ISSUE TITLE
QueryContinuationAsync never returns

### ISSUE THREAD

**Issue by markkesty** [developerforce/Force.com-Toolkit-for-NET#282]
I am using your toolkit to retrieve more than 2,000 records from Salesforce. I call QueryAsync and get back the first 2,000 records. The "Done" flag is false. I then call QueryContinuationAsync<T>(result.NextRecordsUrl); and the call never returns.

I tried the same call from Postman and it continues to return all the records until the end on subsequent calls.

Here is my code:
```
public async Task<List<T>> GetSalesforceQueryResult<T>(string query)
        {
            var records = new List<T>();
            var force = _forceClientService.InitializeForceClient();
            try
            {
                var result = force.QueryAsync<T>(query).Result;
                records.AddRange(result.Records);
                while (!result.Done)
                {
                    result = await force.QueryContinuationAsync<T>(result.NextRecordsUrl);
                    records.AddRange(result.Records);
                }
            }
```

(I left out the catch block)

**Comment by markkesty** [comment]
Anyone?

**Comment by wadewegner** [comment]
If this is still an issue (see latest updates to code) please re-open with more specifics.
