### ISSUE TITLE
MVC - IsAuthentication and Logout issue

### ISSUE THREAD

**Issue by rajurh** [developerforce/Force.com-Toolkit-for-NET#287]
I'm looking into the sample of WebServerOAuthFlow where on successful authentication i am getting a token but  Request.IsAuthenticated is coming has false. Now my question is through out the application if I want to check if application is authenticated how do i check because  Request.IsAuthenticated is coming has false.

Also can you please show the logic for logout functionality please?

**Comment by wadewegner** [comment]
I have removed those samples, as they were no longer working -- several generations old.

If you're having this problem, can you please share a specific code sample/use case?

I'm going to close. Please re-open if appropriate.
