### ISSUE TITLE
1.4 Beta for a year?

### ISSUE THREAD

**Issue by crtjr64** [developerforce/Force.com-Toolkit-for-NET#290]
When I performed the normal install for this package it installed the 1.3 version and several methods didn't work. I wasn't until I lost a day of work, that I learned of the 1.4 beta version. After I installed that package, it worked and so did the Run Async methods... of course, this was after it made a liar out of me and I told my team lead that the methods weren't there... and of course, when we searched for it, there it was... so thanks for that! It seems to be working fine for me though, when are  yo going to stop confusing people and graduate the beta version

**Comment by wadewegner** [comment]
I'm sorry for the trouble.

At this point, I'm not going to release an update and promote 1.4. Instead, I'm planning to release a new 2.0.0 package that supports net core/standard.
