### ISSUE TITLE
How to use CreateAsync when object contains apostrophe

### ISSUE THREAD

**Issue by ARobsonAxco** [developerforce/Force.com-Toolkit-for-NET#292]
I keep getting an error when trying to use CreateAsync if the object being submitted contains a field eg LastName which contains an apostrophe. 

How do I escape or encode the value using C# eg O'Malley?

Salesforce accepts the value O'Malley if I type it into the Salesforce web client directly. 

The problem seems to be with the Force.com toolkit

**Comment by ARobsonAxco** [comment]
My error. closing this

**Comment by kevindenham** [comment]
> 
> 
> My error. closing this

Just curious, what was your error?  I'm having this same issue.  
Salesforce.Common.ForceException: Contact where Email = 'user.o'neill@domain.com' ^ ERROR at
