### ISSUE TITLE
Unsafe Disposal in ForceClient and AuthenticationClient

### ISSUE THREAD

**Issue by tdinucci** [developerforce/Force.com-Toolkit-for-NET#335]
Both the AuthenticationClient and ForceClient classes accept HttpClient's into certain constructor overloads.  This is something I'd like to make use of because MS recommend that you instantiate as few HttpClients per process as possible.

The problem is that both AuthenticationClient and ForceClient implement IDisposable and they blindly dispose of HttpClients even if they were injected into instances. 

Would you accept a pull request where I prevent HttpClients being disposed of if they were injected?

**Comment by jrsteele23** [comment]
I concur. This is problematic.  The ForceClient and AuthenticationClient should not be disposing the HttpClients if they are passed in. Unless someone can explain why the HttpClients should be disposed all the time please accept this change.

**Comment by wadewegner** [comment]
@tdinucci I would accept a pull request for this. Thanks!

**Comment by jrsteele23** [comment]
@tdinucci do you have the solution coded already? Is there any way I can help or assist?

**Comment by tdinucci** [comment]
@jrsteele23 I came up with a solution that was satisfactory for the project I was working on at the time (6 months ago) without forking this project.

Please feel free to pick this up yourself.

**Comment by wadewegner** [comment]
I've merged @jrsteele23's addition. I'll close this for now. Please re-open if there are additional issues.
