### ISSUE TITLE
Meta data

### ISSUE THREAD

**Issue by aday12345** [developerforce/Force.com-Toolkit-for-NET#343]
can you use this api do get meta data??? for example i want to get a list of the countries and states from salesforce

**Comment by marknadig** [comment]
Yes, I've used DescribeAsync to get metadata for objects (Accounts, Opportunities, etc.).
https://github.com/developerforce/Force.com-Toolkit-for-NET/pull/320/

**Comment by aday12345** [comment]
thanks, I will give it a try
do you have an example on how i would get a list of counties?

**Comment by marknadig** [comment]
I don't. Focetoolkit is based on the REST api, so should be able to get the list of values if you have right object name https://developer.salesforce.com/forums/?id=906F000000092QuIAI

**Comment by aday12345** [comment]
Thanks for your help :)
