### ISSUE TITLE
ForceClient QueryAsync not doing anything

### ISSUE THREAD

**Issue by Welborn09** [developerforce/Force.com-Toolkit-for-NET#346]
I have tried both QueryAsync and QueryByIdAsync and both calls never return and no exceptions are thrown. I can't figure out what is wrong with it but I need these calls to complete. 

Are there any log files that are created that I can view? 

My call is pretty simple:
var contact = await sfClient.QueryAsync<Contact>("SELECT Id, Name, Email FROM Account");

Edit/Update: The real query is "SELECT Id, Name FROM Account" since Email doesn't seem to be a valid column.

I switched back to using ForceClient and am able to step all the way through the JsonHttpClient class and into the BaseHttpClient class (Salesforce.Common.Internals). What is happening now is that in the HttpGetAsync(Uri uri) method line 54, returns successful and it goes to line 57 (return response) but it never returns, which is odd. I have breakpoints just after the parent caller (plus I F10) and it hangs.

Still tracing it but either it's an IDE bug or async bug.

**Comment by RobHibinger** [comment]
I am having the same issue. Very simple query as well. Just sits and waits. I let it run for a while with no results. The request just hangs.

**Comment by birgirthor** [comment]
Have you tried to using httpclient with logginghandler ?
Sometimes that gives a hint was is stalling...

--------------
   jsonClient = new System.Net.Http.HttpClient(new LoggingHandler( new HttpClientHandler() ));
   xmlClient = new System.Net.Http.HttpClient(new LoggingHandler( new HttpClientHandler() ));

   var client = new ForceClient(this.InstanceUrl, this.AccessToken, this.Version, jsonClient, xmlClient);

---------
public class LoggingHandler : DelegatingHandler
    {
        public LoggingHandler(HttpMessageHandler innerHandler)
            : base(innerHandler)
        {
        }

        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            
            Console.WriteLine("Request:");
            Console.WriteLine(request.ToString());
            if (request.Content != null)
            {
                Console.WriteLine(await request.Content.ReadAsStringAsync());
            }
            Console.WriteLine();

            HttpResponseMessage response = await base.SendAsync(request, cancellationToken);

            Console.WriteLine("Response:");
            Console.WriteLine(response.ToString());
            if (response.Content != null)
            {
                Console.WriteLine(await response.Content.ReadAsStringAsync());
            }
            Console.WriteLine();

            return response;
        }
    }

**Comment by Welborn09** [comment]
I appreciate the response and tip, I was able to find what my problem is by forking the project and running it locally.

What I found is that the HttpGetAsync(Uri uri) method is returning a 404, but not funneling up the error.
What is even more odd is that Uri is this: 'https://na{removed by me}.salesforce.com/services/data/00D4P0000010zRg!ARwAQFUEfgeqSsDaMg9q3hZog.L3unMOfALCpIgezq_nyGcP0HTdPTzQoerOdNqxVEmvq5yikAGNdLYO7wCKqRH5LbEG8mbz/SELECT%20Id,%20Name,%20Email%20FROM%20Account'

I wouldn't expect that to be the Uri..I would expect the OAuth to be at the end of the string and look more like this:
https://na132.salesforce.com//services/data/v46.0/query?q=SELECT+name+from+Account&oauth_token=00D4P0000010zRg!ARwAQFUEfgeqSsDaMg9q3hZog.L3unMOfALCpIgezq_nyGcP0HTdPTzQoerOdNqxVEmvq5yikAGNdLYO7wCKqRH5LbEG8mbz

or something similar.

**Comment by Welborn09** [comment]
Disregard the last message. I switched from ForceClient to using the JsonHttpClient to see what would happen and I didn't pay attention to the parameter difference. I was putting the accessToken with the version or similar. 

So I am getting the correct Uri now but it is coming back with 404 method not found, I am using v46.0 api. I will have to double check their api documentation to see if the parameters have changed with that route.

**Comment by Welborn09** [comment]
Update:
   I was finally able to get 'QueryAsync' to work. Inside the JsonHttpClient class ->HttpGetAsync<T> (line 40) I modified line 44 by removing the 'await'. With that present it hangs, after removing it I was able to get results back. 

@dcarroll @wadewegner

**Comment by chiranjeeviO** [comment]
Hi All,

I am using Develop[erForce.Force (2.0.7) NuGet package, I am having the same issue, could you please help me on this.

var model = CreateSaleforceClient();

        var accts = new List<dynamic>();
        string query = "Select Id, Name, LastModifiedDate FROM Account ";
        
        var accountsResults = await model.SalesforceClient.QueryAsync<dynamic>(query).ConfigureAwait(false);

Will be thankful in advance.

Thanks
Jeevi

**Comment by jrsteele23** [comment]
Can you wrap the QueryAsync in a try/catch and report if an exception is being thrown and what the exception message is. I have a hunch as to what might be happening but need more info.

**Comment by Welborn09** [comment]
@chiranjeeviO - I would ensure your method 'CreateSalesforceClient' is an async Task<> then change the usage to this:
    var model = Task.Run(() => CreateSalesforceClient()).Result;

**Comment by Welborn09** [comment]
@jrsteele23 - I was able to step through the forceClient code and found that the initial exception was due to a bad field name in my query. But I think since I wasn't properly using the async/task it wasn't funneling up.

Meaning: By using Task.Run() (as my previous post) I was finally able to get any exception back.

**Comment by jrsteele23** [comment]
It sounds like this is resolved. If so, can you please close this issue? Thanks!
