### ISSUE TITLE
Travis CI tests are failing for pull requests

### ISSUE THREAD

**Issue by jrsteele23** [developerforce/Force.com-Toolkit-for-NET#349]
In the public void Init() method of CommonFunctionalTests.cs it appears the following is returning null when Travis CI is running the tests: 

`private static string _consumerKey = ConfigurationManager.AppSettings["ConsumerKey"];`

I don't know what or where or who needs to set these app settings so they are correct and available to Travis CI. Please help.

**Comment by jrsteele23** [comment]
@wadewegner  I think this will need you. to fix.

**Comment by wadewegner** [comment]
I should add this to the README. You can use your own org -- create a DE org, and then set exports in your command line like this:

![image](https://user-images.githubusercontent.com/746259/62989854-8e677b00-bdfe-11e9-9f4f-ada9c7369726.png)
