### ISSUE TITLE
.Net 4.0 - Error compile - type or namespace name 'Salesforce' could not be found

### ISSUE THREAD

**Issue by ghost** [developerforce/Force.com-Toolkit-for-NET#35]
Hi,

Thanks for you work on the DevelopperForce Toolkit.
In the readme document, the framework .Net 4.0 seems compatible with the toolkit.
The goal of my application is to read from Salesforce a table (as Account). The server used to execute the batch is a Windows 2003-R2 operating system.
So, I need to compile my project in .Net 4.0 framework, but when I do it Visual Studio find an error.

Here, you can find the step to reproduce my issues in Visual Studio 2012 :
- Create an ConsoleApp project in C#
- I set the target framework to version 4.0
- By Nuget Package Console, I install the last version of DevelopperForce.Force (version 0.4.6)
- Build : 0 errors, 16 warnings

> The primary reference "Salesforce.Common" could not be resolved because it has an indirect dependency on the framework assembly "System.Collections, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "Salesforce.Common" or retarget your application to a framework version which contains "System.Collections, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".   Test
- I add the using command line `using Salesforce.Force;`
- Build : 1 errors, 16 warnings

> The type or namespace name 'Salesforce' could not be found (are you missing a using directive or an assembly reference?)

I would like to know if you have a solution to run/use the toolkit on the .Net framework 4.0 ?

Regards,

Kikisaeba
(french developper)

**Comment by scanspeak** [comment]
I don't get it. What does it mean "I removed support for .NET 4.0"? There are a lot of enterprise applications in development that use .NET 4.0.
I can remove what I want in my home project. I cannot remove anything I personally want from anything I develop. I cannot believe it is official SalesForce package. Well, I cannot use it.
By the way, the documentation is still not updated. Not a word that .NET 4 is obsolete.

**Comment by dfbuild** [comment]
This is not an official package. I work on this in my own time.

You can easily fork this entire repo and target .NET 4.0.
