### ISSUE TITLE
Can't create Windows Store App package

### ISSUE THREAD

**Issue by gartmeier** [developerforce/Force.com-Toolkit-for-NET#51]
I can't create a Windows Store App package, because it fails the application certification with the following reasons:

Error Found: The debug configuration test detected the following errors:
- The binary Salesforce.Common.dll is built in debug mode.
- The binary Salesforce.Force.dll is built in debug mode.

I installed the latest version of the Force.com Toolkit through NuGet.

**Comment by meenanarendra** [comment]
We have this package install <package id="DeveloperForce.Force" version="1.1.1" targetFramework="portable-net45+win+wp80+MonoAndroid10+xamarinios10+MonoTouch10" />

I still see the error with windows app certification kit.

Debug configuration
Error Found: The debug configuration test detected the following errors:
The binary Salesforce.Force.dll is built in debug mode.
The binary Salesforce.Common.dll is built in debug mode.
Impact if not fixed: Windows Phone Store doesn’t allow a debug version of an app.
How to fix: Please make sure the app isn't linking to any debug versions of a framework and it is built with the release configuration with optimization enabled.

**Comment by meenanarendra** [comment]
Thank you for providing the release to fix this issue. I have updated DeveloperForce.Force.1.2.1 package and that resolved the issue.

**Comment by wadewegner** [comment]
Glad to hear it. Interestingly, I did nothing different. I wonder if packaging or publishing broke during our previous publish. We'll track it better moving forward.

**Comment by meenanarendra** [comment]
I get below error message after update from client.QueryAsync method

Could not load file or assembly 'System.IO.Compression, Version=3.9.85.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified. at Salesforce.Common.HttpContentCompressedDataExtensions.<ReadAsDecompressedStringAsync>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Salesforce.Common.HttpContentCompressedDataExtensions.ReadAsDecompressedStringAsync(HttpContent responseContent)
   at Salesforce.Common.ServiceHttpClient.<HttpGetAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DSA.Mobile.Shared.Repositories.CustomerRepository.<GetContacts>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DSA.Mobile.Shared.SalesForceServices.CustomerService.<SearchCustomersAsync>d__e.MoveNext()

**Comment by meenanarendra** [comment]
Hi Wade,

We are using sales force git hub library to retrieve the data from sales
force. We have field in a user table *User.SmallPhotoUrl. We want to
display this image url into our application as image. *

*Here is sample image url. *
https://c.na7.content.force.com/profilephoto/729A0000000Pee2/T



How we can download this image using force client to bind to image control.
This url required authentication and we can download using browser.

Select *User.SmallPhotoUrl* From AccountTeamMember Where IsDeleted=false " +
           "and accountId='{0}'"

On Tue, Nov 17, 2015 at 7:37 PM, Wade Wegner <notifications@github.com>
wrote:

> Glad to hear it. Interestingly, I did nothing different. I wonder if
> packaging or publishing broke during our previous publish. We'll track it
> better moving forward.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/developerforce/Force.com-Toolkit-for-NET/issues/51#issuecomment-157569434>
> .
>



-- 
Thanks & Regards,
Narendra K Meena
502-994-4825
