### ISSUE TITLE
Signed version of Salesforce assemblies available?

### ISSUE THREAD

**Issue by lschuste** [developerforce/Force.com-Toolkit-for-NET#53]
When I use the Saleforce.Force nuget package I get the following compile time errors:

Error   1   Assembly generation failed -- Referenced assembly 'Salesforce.Common' does not have a strong name  
Error   2   Assembly generation failed -- Referenced assembly 'Salesforce.Force' does not have a strong name    

That's because my assemblies are signed while the Salesforce assemblies are not.

Will there be signed assemblies of the assemblies available in future?

**Comment by wadewegner** [comment]
For what it's worth, I was convinced this was needed and added am now signing the assemblies with a strong name key: https://github.com/developerforce/Force.com-Toolkit-for-NET/commit/3b15bd5a5df3095884e3edff4f099645a331e013
