### ISSUE TITLE
The format of value 'https://login.salesforce.com/services/oauth2/token/v30.0' is invalid.

### ISSUE THREAD

**Issue by lefthook123** [developerforce/Force.com-Toolkit-for-NET#81]
Hi, thank you for providing this toolkit.
I tried the code in a Console Application it worked well.
However, when I moved my code to an MVC application and ran the code through an Action method, it gives me error  "The format of value 'https://login.salesforce.com/services/oauth2/token/v30.0' is invalid.".

Do you know what's happening?  Thank you very much!

    public ActionResult AdvisorsMap()
        {
            List<AdvisorMapInfo> result = AdvisorsMapBL.getAdvisorsAsync().Result;
            return View(result);            
        }

    public static async Task<List<AdvisorMapInfo>> getAdvisorsAsync()
        {
            var auth = new AuthenticationClient();
            //Authenticate with Salesforce
            var url = IsSandboxUser.Equals("true", StringComparison.CurrentCultureIgnoreCase)
                ? "https://test.salesforce.com/services/oauth2/token"
                : "https://login.salesforce.com/services/oauth2/token";

            await auth.UsernamePasswordAsync(ConsumerKey, ConsumerSecret, Username, Password, url);           
            var client = new ForceClient(auth.InstanceUrl, auth.AccessToken, auth.ApiVersion);
            const string qry = "SELECT Name,Primary_Contact__c,Asset_Range_Lower__c,Asset_Range_Upper__c,BillingAddress FROM Account WHERE (Account_Type__c='Advisor' or Account_Type__c='provider')";
            var accts = new List<AdvisorMapInfo>();
            var results = await client.QueryAsync<AdvisorMapInfo>(qry);
            var totalSize = results.totalSize;
            accts.AddRange(results.records);
            var nextRecordsUrl = results.nextRecordsUrl;
            if (!String.IsNullOrEmpty(nextRecordsUrl))
            {
                while (true)
                {
                    var continuationResults = await client.QueryContinuationAsync<AdvisorMapInfo>(nextRecordsUrl);
                    totalSize = continuationResults.totalSize;
                    accts.AddRange(continuationResults.records);
                    if (string.IsNullOrEmpty(continuationResults.nextRecordsUrl)) break;
                    nextRecordsUrl = continuationResults.nextRecordsUrl;
                }
            }
            return accts;
            
        }

    }

**Comment by StanleyGoldman** [comment]
I'm currently seeing this error, what was wrong?

**Comment by wadewegner** [comment]
Will look into it.

**Comment by wadewegner** [comment]
Not able to reproduce.
