### ISSUE TITLE
HttpStatusCode is missing in the ForceException and ForceAuthException

### ISSUE THREAD

**Issue by luciazaliberova** [developerforce/Force.com-Toolkit-for-NET#82]
In our application we are querying `Account` using following code:

			ForceClient client = new ForceClient(instanceUrl, accessToken, apiVersion);
			string query = "SELECT Id, Name, AccountNumber, ShippingAddress, BillingAddress, Phone FROM Account");

			try {		
				QueryResult<Account> queryResults = await client.QueryAsync<Account>(query);
			}
			catch (ForceException exception)
			{
				throw new HttpResponseException(Request.CreateErrorResponse(exception.HttpStatusCode, exception.Message));
			}

In case that the accessToken is expired the `client.QueryAsync<Account>(query)` throws `ForceException`. It would be very helpful to know that the client is not authorized and need to perform the login process. The `ForceException` should include also `HttpStatusCode` received from the server, so that we can distinguish different error states.
The `ForceException` class constructor could have another overload with `httpStatusCode`:

		public ForceException(string error, string description, HttpStatusCode httpStatusCode)
			: this(ParseError(error), description)

**Comment by wadewegner** [comment]
Wow. A long time coming.

Here's the pull request for this feature upgrade: https://github.com/developerforce/Force.com-Toolkit-for-NET/pull/205

I'll leave it here for just a bit and then merge if no one has any problems with it.

/cc @dcarroll

**Comment by wadewegner** [comment]
Why not? I went ahead and merged the change.
