### ISSUE TITLE
Incorrect error handling in the AuthenticationClient.WebServerAsync 

### ISSUE THREAD

**Issue by luciazaliberova** [developerforce/Force.com-Toolkit-for-NET#83]
To reproduce:

	tokenRequestEndpointUrl = "https://login.salesforce.com/services/oauth2/authorizeee"; // typo in the url
	await auth.WebServerAsync(consumerKey, consumerSecret, callbackUrl, authCode, tokenRequestEndpointUrl);

Inside `WebServerAsync` method the HTTP request returns html error page and therefore can't be deserialized into AuthErrorResponse type in the following code:

        public async Task WebServerAsync(string clientId, string clientSecret, string redirectUri, string code, string tokenRequestEndpointUrl)
        {
                ...
                AuthErrorResponse errorResponse = JsonConvert.DeserializeObject<AuthErrorResponse>(response);
                ...
        }

**Comment by wadewegner** [comment]
Okay. Finally got around to this one too. =)

https://github.com/developerforce/Force.com-Toolkit-for-NET/pull/205

/cc @dcarroll

**Comment by wadewegner** [comment]
Merged.
