### ISSUE TITLE
Unable to create ChatterClient with auth after update

### ISSUE THREAD

**Issue by TThomasWelk** [developerforce/Force.com-Toolkit-for-NET#84]
This worked just fine until I updated via Nu-get yesterday.

The only difference is the userAgent is no longer required when creating the AuthenticationClient.

Please advise?

auth.APIVersion was 3.0 and is now 3.2

I tested old code on another developers PC and he can Create the client so Saleforce creds are still valid.

private async Task<bool> GetClientsAsync()
        {
            try
            {
                string url = IsSandboxUser.Equals("true", StringComparison.CurrentCultureIgnoreCase)
                    ? "https://test.salesforce.com/services/oauth2/token"
                    : "https://login.salesforce.com/services/oauth2/token";

                var auth = new AuthenticationClient();

                Debug.WriteLine(url);

                await auth.UsernamePasswordAsync(ConsumerKey, ConsumerSecret, Username, Password, url).ConfigureAwait(false);

                ChatterClient = new ChatterClient(auth.InstanceUrl, auth.AccessToken, auth.ApiVersion);

                ForceClient = new ForceClient(auth.InstanceUrl, auth.AccessToken, auth.ApiVersion);
                
            }
            catch (ForceAuthException ex)
            {
                ex.Data.Add("SecurityToken", SecurityToken);
                ex.Data.Add("ConsumerKey", ConsumerKey);
                ex.Data.Add("ConsumerSecret", ConsumerSecret);
                ex.Data.Add("Username", Username);
                ex.Data.Add("Password", "********");
                ex.Data.Add("IsSandboxUser", IsSandboxUser);
                Log.Error(ex);
                throw;
            }

            return true;
        }

**Comment by wadewegner** [comment]
@TThomasWelk it looks like you resolved this. Additionally, all the unit tests are passing for the ChatterClient and I was able to test myself.

I'm going to close this. If any of you are having issues, can you please open a new issue and share explicit repro steps? Thank you!
