### ISSUE TITLE
Feedback for Travis CI C# support

### ISSUE THREAD

**Issue by akoeplinger** [developerforce/Force.com-Toolkit-for-NET#86]
Hey, I'm one of the contributors of the [Travis CI C# support](http://blog.travis-ci.com/2014-12-10-community-driven-language-support-comes-to-travis-ci/) and saw that you enabled it on your repository.

I'd be really interested to hear how your experience was. Is the [documentation](http://docs.travis-ci.com/user/languages/csharp/) easy to understand? Can we improve something? Did you encounter any problems?

Thanks for your time :smile:

**Comment by wadewegner** [comment]
Sorry for the delayed response, @akoeplinger.

Actually, not so well yet. Can you take a look and help me understand why this keeps failing? Looks like paths have changed or something?

**Comment by wadewegner** [comment]
I was able to sort this out, @akoeplinger! Take a look.

**Comment by akoeplinger** [comment]
Cool, looks fine :)
