### ISSUE TITLE
IForceClient interface is missing the QueryContinuationAsync method.

### ISSUE THREAD

**Issue by jicornelius** [developerforce/Force.com-Toolkit-for-NET#87]
I was trying to use the IForceClient interface but realized I could not get subsequent records using the QueryContinuationAsync method because the interface only includes the QueryAsync method.  I was forced to not use the interface and use the ForceClient class directly.

**Comment by wadewegner** [comment]
I'll fix it. Thanks.

**Comment by wadewegner** [comment]
Apologies for taking so long on this! Fixed here: https://github.com/developerforce/Force.com-Toolkit-for-NET/commit/12d52616e22081ae06c3aac76e0bf3decb8817a0

Will release in next NuGet package.

**Comment by wadewegner** [comment]
I have packaged and pushed the update to DeveloperForce 0.6.5 - https://www.nuget.org/packages/DeveloperForce.Force/
