### ISSUE TITLE
Consider signing assemblies

### ISSUE THREAD

**Issue by peranborkett** [developerforce/Force.com-Toolkit-for-NET#89]
To improve nuget usability, currently you can not sign your own assemblies that reference the Salesforce dll's as the Salesforce dll's are not signed.

**Comment by wadewegner** [comment]
I feel as if I've gotten enough feedback that this would be useful that we should figure out an easy way to do this. I will investigate.

**Comment by wadewegner** [comment]
Added. https://github.com/developerforce/Force.com-Toolkit-for-NET/commit/8a947a48802f97357fb283721b6ce17f2f9a87c7
