### ISSUE TITLE
Cannot update field.

### ISSUE THREAD

**Issue by Telarian** [developerforce/Force.com-Toolkit-for-NET#90]
I'm trying to update the "AccountSource" field on the Account object in Salesforce via the following code:
```
Dim a As Object = New ExpandoObject()
a.AccountSource = "Test"
Await client.UpsertExternalAsync("Account", "External_Id__c", 12345, a)
```
It gives me the following error: "No such column 'AccountSource' on sobject of type Account"

I know the field should exist. I can see it in Salesforce. I believe I have the name correct according to the documentation and what I see in the Salesforce setup.
I have also done a very similar operation using the "LeadSource" field on the Lead (which is a very similar field using the same picklist) and it worked properly.

Perhaps I am just doing something wrong, but if so, I can't see where. I don't know that it's a bug in the toolkit, but I don't know what else it could be.
Any assistance would be greatly appreciated.

Thanks

**Comment by wadewegner** [comment]
It's been awhile since I've used VB, so apologies for switching to C#.

The first time I run this I get the error `Salesforce.Common.ForceException : Required fields are missing: [Name]` given that the record doesn't exist already. So, I've modified the code slightly to include a `Name` in the `ExpandoObject`:

``` c#
[Test]
public async void UpdateExternalAsync_AccountSource()
{
    dynamic a = new ExpandoObject();
    a.AccountSource = "TestAccountSource";
    a.Name = "TestAccountName";

    const string objectName = "Account";
    const string fieldName = "External_Id__c";

    await CreateExternalIdField(objectName, fieldName);

    var externalId = Convert.ToString(DateTime.Now.Ticks);

    var success = await _client.UpsertExternalAsync(objectName, fieldName, externalId, a);
    Assert.IsNotNull(success);
    
    a.AccountSource = "TestAccountSource2";
    
    success = await _client.UpsertExternalAsync(objectName, fieldName, externalId, a);
    Assert.IsNotNull(success);
}
```
This runs as expected.

Here's the first response ...
```
HTTP/1.1 201 Created
Date: Mon, 26 Jan 2015 20:07:55 GMT
Set-Cookie: BrowserId=zOSemo7PQrS9nVqlN0H2RQ;Path=/;Domain=.salesforce.com;Expires=Fri, 27-Mar-2015 20:07:55 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Sforce-Limit-Info: api-usage=176/15000
Location: /services/data/v32.0/sobjects/Account/001F000001N05ypIAB
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked

35
{"id":"001F000001N05ypIAB","success":true,"errors":[]
1
}
0
```

... and the second response ...

```
HTTP/1.1 204 No Content
Date: Mon, 26 Jan 2015 20:07:56 GMT
Sforce-Limit-Info: api-usage=176/15000
```

Am I missing something?

Sorry for your trouble!

**Comment by wadewegner** [comment]
I have packaged and pushed the update to DeveloperForce 0.6.5 - https://www.nuget.org/packages/DeveloperForce.Force/

**Comment by Telarian** [comment]
Ya, I don't get it. It should work. It just doesn't.
![image](https://cloud.githubusercontent.com/assets/959980/6116798/e223ddbe-b06c-11e4-9627-c87f83efee50.png)

**Comment by Telarian** [comment]
Ya, I don't get it. It should work. It just doesn't.
![image](https://cloud.githubusercontent.com/assets/959980/6116828/22a4d668-b06d-11e4-84da-0c528313f90b.png)

**Comment by Telarian** [comment]
Do the exact same thing without the AccountSource field and it works fine.

**Comment by wadewegner** [comment]
Please use Fiddler and see what the response is that comes back. Confirm the data is in the response.

I'll close this for now but please open it if you still have the issue.

**Comment by Telarian** [comment]
Turned out the field was marked as not accessible even by system administrators. That was just not something I realized could have been a problem. I do now.

Thanks for all your patience and help.
