### ISSUE TITLE
Queries with "+" fail. Salesforce wants them escaped to %2B

### ISSUE THREAD

**Issue by davidtwamley** [developerforce/Force.com-Toolkit-for-NET#93]
Create a lead in Salesforce with email address forcetoolkit+issue@gmail.com and then run:

    string query = "SELECT id FROM Lead WHERE email = 'forcetoolkit+issue@gmail.com'";
    var result = client.QueryAsync<T>(query);

Zero results. Fiddler shows this REST call (I added wrapping):

    GET /services/data/v32.0/query?
    q=SELECT%20Id%20FROM%20Lead%20WHERE%20
    email%20=%20'forcetoolkit+issue@gmail.com' HTTP/1.1

Notice the `+`. Reissue and Edit in fiddler changing `+` to `%2B` and you get results. At the moment we can workaround it in our code with:
    
    string query = "SELECT id FROM Lead WHERE email = 'forcetoolkit+issue@gmail.com'";
    query = query.Replace("+", "%2B");  // Workaround: escape + to %2B ourselves
    var result = await client.QueryAsync<T>(query);

But, I think it would be better to fix it in the library. Maybe [here](https://github.com/developerforce/Force.com-Toolkit-for-NET/blob/master/src/ForceToolkitForNET/ForceClient.cs#L34) or [here](https://github.com/developerforce/Force.com-Toolkit-for-NET/blob/master/src/CommonLibrariesForNET/ServiceHttpClient.cs#L46). Jon Skeet suggests using [Uri.EscapeDataString](http://stackoverflow.com/a/3460455/864030) for this issue.

Thanks! Really enjoy using this library btw. Nice work!

**Comment by wadewegner** [comment]
Great find, @davidtwamley! I have fixed in this commit: https://github.com/developerforce/Force.com-Toolkit-for-NET/commit/0b33371684eb4ebf670dc25651bc5b350f2f2767.

I will create a new NuGet today (once I get a few more issues resolved).

**Comment by wadewegner** [comment]
I have packaged and pushed the update to DeveloperForce 0.6.5 - https://www.nuget.org/packages/DeveloperForce.Force/

**Comment by davidtwamley** [comment]
0.6.5 fixed it up nice. Thank you, sir.
