### ISSUE TITLE
Force.com Toolkit for .NET class construct with QueryAsync when SQL query has a child/parent relationship

### ISSUE THREAD

**Issue by acccollin** [developerforce/Force.com-Toolkit-for-NET#94]
I'm running the following query which contains a child => parent relationship between Case and Account - and contains the Account.Name in the SELECT:
        string query = "SELECT Case.CaseNumber,Case.Account.Name,Case.Status FROM Case WHERE Status != 'Closed' AND OwnerId IN (SELECT Id FROM User WHERE Email = '" + userEmail + "') ORDER BY Account.Name";
        var results = await client.QueryAsync<CaseWorkload>(query);

CaseWorkload class was defined as:
public class CaseWorkload
{
  public string CaseNumber { get; set; }
  public string Status { get; set; }
  public string AccountName { get; set; }
}

I am unable to retrieve the AccountName information as the returned SQL shows "Account.Name" and I couldn't find a way in SOQL to alias a column. How the class would need to be created considering the given query?

**Comment by wadewegner** [comment]
I'd recommend using `dynamic` first and capturing the response using Fiddler. Then go to http://json2csharp.com/ and paste the Json to create the appropriate class. Give it a try and let me know.

**Comment by wadewegner** [comment]
I assume this was fixed (or abandoned).

**Comment by bogomal** [comment]
@wadewegner I had the same problem and your comment on using the dynamic guided me in the right direction. This is a longish way of doing things - but it works. Thanks.
