### ISSUE TITLE
How can i parse Account.Name?

### ISSUE THREAD

**Issue by honeyhead** [developerforce/Force.com-Toolkit-for-NET#95]
string query = "Select AccountId, Account.Name, Email, Phone, Name, Title, MobilePhone from Contact ";

this is my query . but i can't get Account.Name <- this is reference field & contain dot

how can i deserialize insert into      "public string AccountName { get; set; }" ???

**Comment by Cyphtor** [comment]
Make another class for it to deserialize properly into or use a formula field to pull the account name.

**Comment by wadewegner** [comment]
That's right. Create and `Account` and `Contact` class as @Cyphtor states. Then call `QueryAsync` as follows:

``` c#
var queryResult = await _client.QueryAsync<Models.QueryTest.Contact>(
    "SELECT AccountId, Account.Name, Email, Phone, Name, Title, MobilePhone FROM Contact");
```

Hope that helps!

**Comment by wadewegner** [comment]
In case it helps, here's a unit test I've added: https://github.com/developerforce/Force.com-Toolkit-for-NET/blob/master/src/ForceToolkitForNET.FunctionalTests/ForceClientTests.cs#L104
