### ISSUE TITLE
ForceClient.CreateAsync() method never returns

### ISSUE THREAD

**Issue by momerjaved** [developerforce/Force.com-Toolkit-for-NET#96]
Hi,
I am getting an issue with CreateAsync method of ForceClient that the method call never returns back. It doesn't come back even with an exception. I have tried the same code in a console app and it is working fine but when I use it in my actual project it shows the behavior which I have just explained. It's quite difficult for me to be sharing the code because it has a span over multiple projects. One thing to note is that I am loading dlls using MEF into the project and then making QueryAsync and CreateAsync calls from one of those dlls. The QueryAsync calls works fine and returns with records from Salesforce but CreateAsync just seems to be stuck. Any ideas / hints in this regard ? Thanks.

**Comment by jeryanders** [comment]
I had this problem too. Just some things to check:
1. Make sure you have all the required fields populated.
2. Make sure the object make matches the Salesforce object name (Lead, Account, or the name of your custom object)
3. Make sure any field with types like Phone or Email match the pattern of a phone number or email address. 
I hope that helps.

**Comment by wadewegner** [comment]
Let us know if this is still an issue.

**Comment by jagilbert27** [comment]
I am having the same problem: My test console app works fine, but QueryAsync never returns when called from a windows app.
- Windows 10
- Visual Studio 2015, C#,  .Net Framework: 4.6.1
- DeveloperForce: 1.3.0, Newtonsoft.Json 8.0.3

I make the following call from a test console app and it works as expected, but the same call, with the same soql and the same authentication never returns and no exception is thrown in my windows forms app:
`var response = await client.QueryAsync<dynamic>(soql);`
If i change the soql query to make it invalid, I DO get an exception, so I know that my requested is being successfully authenticated and executed on the server.
I DON'T have references to System.ComponentModel.Composition or System.Composition, therefore MEF doesn't come in to play.

**Comment by patrickrobbins** [comment]
If you are using async, make sure you are not thread locked.  Try adding
the configureawait(false)
http://blog.stephencleary.com/2012/02/async-and-await.html

**Comment by jagilbert27** [comment]
Thanks Patrick, I'll try that.
I just noticed that this works and I see all my records in the console log: 
```
public void LoadData(){  
    GetMyStuffAsync(); 
}
public async Task GetMyStuffAsync() {
   ...await client.QueryAsync<dynamic>(soql);...
   Console.Log(theResults)
}
```
but this doesn't log the results and the Task.WaitAll never returns.
```
public void LoadData(){  
   var tasks = new List<Task> { GetMyStuffAsync() };
  Task.WaitAll(tasks.ToArray());
  //never gets here
}
public async Task GetMyStuffAsync() {
   ...await client.QueryAsync<dynamic>(soql);...
   Console.Log(theResults) //never gets here
}
```

**Comment by jagilbert27** [comment]
Thanks again Patrick!  The "ConfigureAwait(false)" did the trick.  This now works as expected:
```
public void LoadData(){  
   var tasks = new List<Task> { GetMyStuffAsync() };
  Task.WaitAll(tasks.ToArray());
}
public async Task GetMyStuffAsync() {
   ...await client.QueryAsync<dynamic>(soql).ConfigureAwait(false);...
   Console.Log(theResults)
}
```
_[SalesForce ForceClient QueryAsync hangs blocks stuck winforms]_

**Comment by wolfen351** [comment]
I'm also having this issue  - query works fine and insert fails. I have copied and pasted the code from the console app which was working. Same security etc. Could it be something external like IIS Express causing this?

ConfigureAwait("false") had no effect

**Comment by wolfen351** [comment]
I'm making an identical object to the console app, so I know it is not directly related to what data i'm sending, it has to be how i'm calling it, or something which differs in web api world

**Comment by chiranjeeviO** [comment]
Hi All,

Please help guys. I do have same issue, My unit test code is working fine, i.e getting results from Salesforce. But the same code, i running via Browser (VS2017 ) IIS Express.

----------------------------------------------------------------------------
var model = CreateSaleforceClient();
            
            var accts = new List<dynamic>();
            string query = "Select Id, Name, LastModifiedDate FROM Account ";
            
            var accountsResults = await model.SalesforceClient.QueryAsync<dynamic>(query).ConfigureAwait(false);
----------------------------------------------------------------------------
Please help me here guys

Cheers
Jeevi
