### ISSUE TITLE
Authentication against Salesforce Sandbox

### ISSUE THREAD

**Issue by indimini** [developerforce/Force.com-Toolkit-for-NET#98]
Hi, first of all, thanks for this library - it has been a huge help on a dev task I'm working on.

I am having issues trying to get username/pwd authentication to work against a Salesforce sandbox.  I tried in the sample projects to set IsSandbox to true in the app.config and it throws an exception.

I've also tried to authenticate with my connected app/user account information from my sandbox to no avail.  What is really odd is that if I use my sandbox app's Consumer key and consumer secret, the authentication will work with the production user credentials but it always fails with sandbox account credentials. In that case, it has authenticated against the production instance and not the sandbox instance.

Thanks for any insights/guidance

**Comment by estrehl** [comment]
What is the exception you are getting? It sounds like perhaps the user acct is not completely authorized within the sandbox environment? I know there were a lot of additional roles/permissions I had to set up for my sandbox user acct in order to get authorization. Our permission set labels might be different, but we do have one titled "API access", for example.

Are you by chance trying the simple console example? How did you get it to build? I am getting bad reference/CLR clashes trying to do so...

**Comment by indimini** [comment]
The exception was some kind of timeout error.  Somebody on our team rebuilt the sandbox last night and I am no longer getting the runtime exception.  It sounds like your hunch was correct re: user account roles/permissions.

I have been testing within the console example.  In my environment, after reconfiguring Nuget to refresh automatically, I just deleted my packages folder and rebuilt.  I did get an error re: path to the Salesforce.force and salesforce.common assemblies.  There was a disconnect between the nuget path and the actual dll locations.  I manually updated the references to the assemblies to point to the correct packages location and the build worked.  Hope that helps.

**Comment by estrehl** [comment]
Cool; glad you are up and running. My issue not yet resolved, but maybe making progress. At least now getting warnings that the salesforce.common and salesforce.force interfaces are targeting/built with the wrong framework... "Ain't nothin' easy", I guess.

**Comment by wadewegner** [comment]
Looks like we had a regression with the samples in one of the last commits (https://github.com/developerforce/Force.com-Toolkit-for-NET/issues/97). I'll fix. Sounds like this particular issue is resolved.
